In [1]:
from jaref_bot.data.http_api import ExchangeManager, BybitRestAPI, OKXRestAPI, GateIORestAPI
from jaref_bot.strategies.arbitrage import find_tokens_to_open_order, get_open_volume, get_best_prices
from jaref_bot.utils.coins import get_step_info, get_min_qty, round_volume, get_price_scale
from jaref_bot.trading.functions import handle_opened_position, handle_close_position, set_leverage, place_market_order
from jaref_bot.data.data_functions import is_data_up_to_date
from jaref_bot.utils.data import round_size

from jaref_bot.db.postgres_manager import DBManager
from jaref_bot.db.redis_manager import RedisManager
from jaref_bot.config.credentials import host, user, password, db_name

import redis
from redis.exceptions import ConnectionError

import sys
import pandas as pd
import polars as pl
import polars.selectors as cs
import numpy as np
import logging
from datetime import datetime
from time import sleep, time
from decimal import Decimal, ROUND_DOWN
import signal
import random, string
import pickle

from asyncio.exceptions import CancelledError
import aiohttp, asyncio
import nest_asyncio
nest_asyncio.apply()

from numba import njit

In [2]:
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(message)s")
logging.getLogger('aiohttp').setLevel('ERROR')
logging.getLogger('asyncio').setLevel('ERROR')
logger = logging.getLogger()

In [3]:
def signal_handler(sig, frame):
    global exit_flag
    print('Завершение работы.')
    exit_flag = True

In [4]:
def check_open_conditions(token: str, 
                          current_orders: pd.DataFrame, 
                          pending_orders: dict, 
                          min_order: float,
                          max_position: float) -> float:
    """
        Функция проверяет условия для открытия нового ордера. Новый ордер будет открыт если:
        - Токена ещё нет ни в текущих ордерах, ни в открытых позициях
        - Токен есть в открытых позициях, но размер позиции позволяет открыть ещё одну сделку.

        Args:
            token - название токена. Например, 'ADA_USDT'.
            current_orders - датафрейм с текущими позициями.
            pending_orders - словарь с текущими ордерами.
            max_position - максимально возможный размер позиции на бирже.
        Return:
            Размер ордера в usdt, который можно открыть.
    
    """
    # Сначала проверяем условие, что такой ордер ещё не открывали
    token_in_positions = token in current_orders['token'].to_list()
    
    token_in_pending = False
    position_size = 0
    for exc, data in pending_orders.items():
        for tok in data:
            if tok == token:
                token_in_pending = True
                position_size += float(data[tok]['qty'])
    if not (token_in_positions or token_in_pending):
        return max_position

    # Проверяем условие, что ордер уже есть среди открытых позиций, но размер позиции позволяет добавить
    if token_in_positions:
        try:
            price = current_orders.filter(pl.col('token') == token)['price'].max()
            opened_position = current_orders.filter(pl.col('token') == token)['usdt_amount'].max()
        
            position_usdt = position_size * price + opened_position
            if position_usdt < max_position - min_order:
                return max_position - position_usdt
        except TypeError: # Ситуация, когда команда на закрытие позиции по этому токену уже отдана, но сам токен из БД ещё не убран
            return False

                
    return False

In [5]:
def check_counter_conditions(token: str, 
                pending_orders: dict, 
                long_exc: str, 
                short_exc: str,
                long_price: float,
                short_price: float) -> bool:
    long_order_status = None
    short_order_status = None
    
    for exc, data in pending_orders.items():
        open_side = data.get(token, {}).get('side', None)
        status = data.get(token, {}).get('status', None)
        price_tick = get_price_scale(coin_information, token, exc + '_linear')
    
        if open_side == 'buy':
            if status == 'filled':
                long_order_status = 'filled'
                order_side = 'sell'
                price = Decimal(short_price) - n_ticks * price_tick
            elif status == 'placed':
                long_order_status = 'placed'
        elif open_side == 'sell':
            if status == 'filled':
                short_order_status = 'filled'
                order_side = 'buy'
                price = Decimal(long_price) + n_ticks * price_tick
            elif status == 'placed':
                short_order_status = 'placed'
    
    # Если ордер открыт только в одну сторону, тогда возвращаем размер и направление встречного ордера
    if (long_order_status == 'filled' and short_order_status is None
               ) or (
        long_order_status is None and short_order_status == 'filled'):

        qty = pending_orders[exc][token]['qty']

        return exc, order_side, qty
    
    return (False, False)

In [6]:
market_fees = {'bybit_spot': 0.001, 'bybit_linear': 0.001, 'okx_spot': 0.001, 'okx_linear': 0.0005,
               'gate_spot': 0.002, 'gate_linear': 0.0005}

In [7]:
logger.info('Инициализируем биржи...')
# ====================================
# Инициация нужных криптобирж, рынков и БД
exc_manager = ExchangeManager()
exc_manager.add_market("bybit_linear", BybitRestAPI('linear'))
# exc_manager.add_market("okx_linear", OKXRestAPI('linear'))
# exc_manager.add_market("gate_linear", GateIORestAPI('linear'))

db_params = {'host': host, 'user': user, 'password': password, 'dbname': db_name}
postgre_manager = DBManager(db_params)

2025-09-08 22:04:45 [INFO] Инициализируем биржи...

In [8]:
# Подготовительный этап. Загружаем техническую инфу по токенам (мин. кол-во и число знаков после запятой)
coin_information = exc_manager.get_instrument_data()

with open("./data/coin_information.pkl", "wb") as f:
    pickle.dump(coin_information, f)

In [9]:
# with open("./data/open_order_history.pkl", "rb") as f:
#     orders_history = pickle.load(f)
    
leverage_change_history = []

#### Pair trading

In [10]:
# from jaref_bot.analysis.utils import make_spread_df_bulk, make_trunc_df, make_df_from_orderbooks, make_spread_df
from zoneinfo import ZoneInfo
from datetime import timedelta
from jaref_bot.utils.pair_trading import get_lr_zscore
from uuid import uuid4
import math
from functools import lru_cache

redis_orders = RedisManager(db_name = 'orders')
redis_orderbooks = RedisManager(db_name = 'orderbooks')

In [11]:
def get_hist_df():
    hour_1_df = postgre_manager.get_orderbooks(exchange='bybit',
                                             market_type='linear',
                                             interval='1h',
                                             start_date=start_time)
    hour_1_df = hour_1_df.with_columns(
            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
        )
    hour_1_df = hour_1_df.drop(cols_to_drop)
    
    hour_4_df = postgre_manager.get_orderbooks(exchange='bybit',
                                         market_type='linear',
                                         interval='4h',
                                         start_date=start_time)
    hour_4_df = hour_4_df.with_columns(
            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
        )
    hour_4_df = hour_4_df.drop(cols_to_drop)

    return hour_4_df, hour_1_df

In [12]:
def round_down(value: float, dp: float):
    return round(math.floor(value / dp) * dp, 6)

In [13]:
@lru_cache
def set_leverage_cached(token, leverage):
    set_leverage(demo=demo, exc='bybit_linear', symbol=token + '_USDT', leverage=leverage)
    logger.info(f'Leverage for {token} changing to {leverage}...')

In [14]:
params = [
(1.0, "IOTA", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "NEAR", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GOAT", "MANA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "SUSHI", "XRP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "DOT", "KSM", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GOAT", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "APT", "ZEN", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IMX", "NEAR", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FIL", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "C98", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONT", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "OGN", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IMX", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "APT", "FIL", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "STG", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GTC", "OP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "STG", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONT", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "MANA", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "APT", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "VET", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "OGN", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONT", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONT", "SAND", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IMX", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "BLUR", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FIL", "SNX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IMX", "SAND", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FIL", "XRP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "C98", "CHZ", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "OGN", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "OGN", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "DOT", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARB", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "MANA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GALA", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONT", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "ONT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "IMX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ROSE", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "SAND", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "VET", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ROSE", "VET", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "DOT", "XRP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "NEAR", "SNX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "SNX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "STG", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ROSE", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GALA", "GMT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "IMX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "DOT", "FIL", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "IMX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "SNX", "XRP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "C98", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "APT", "KSM", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "ONDO", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CELO", "GRT", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "SAND", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "STRK", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "SAND", "ZRX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "STG", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "FLOW", "GTC", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "OGN", "SAND", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "OP", "SNX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "SAND", "SNX", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "SAND", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "XAI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GMT", "ROSE", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "ROSE", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "DOT", "ZEN", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ONDO", "XRP", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "CHZ", "GALA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "VET", "ZK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GTC", "IOTA", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "GRT", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "STRK", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "IOTA", "STG", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "SUSHI", "1h", 18, -2.0, 2.0, -0.5, 0.5),
(1.0, "ARKM", "FLOW", "1h", 18, -2.0, 2.0, -0.5, 0.5)
]

sorted_params = sorted(params, key=lambda x: x[0], reverse=True)

In [15]:
demo = True
exchange = 'bybit'
min_order = 50
max_position = 100
leverage = 2
fee_rate = 0.00055

In [22]:
for _, token_1, token_2, tf, wind, low_in, high_in, low_out, high_out in sorted_params:
    set_leverage_cached(token=token_1, leverage=leverage)
    set_leverage_cached(token=token_2, leverage=leverage)

In [17]:
end_time = datetime.now().replace(tzinfo=ZoneInfo("Europe/Moscow"))
start_time = end_time - timedelta(hours = 48)
cols_to_drop = ('exchange', 'market_type', 'bid_price', 'bid_size', 'ask_price', 'ask_size')

z_score_df = pl.DataFrame()

In [ ]:
# %%time

with_break = False
break_flag = False

postgre_manager = DBManager(db_params)
z_score_buffer = []

while True:
    try:
        time_now = datetime.now()
        ts = int(datetime.timestamp(time_now))
        ct = time_now.strftime('%Y-%m-%d %H:%M:%S')
        
        # --- Подгружаем исторические датафреймы 1 раз в час ---
        try:
            last_updates_1h = (datetime.now(ZoneInfo("Europe/Moscow")) - hour_1_df[-1]['bucket'][0]).seconds
        except NameError:
            hour_4_df, hour_1_df = get_hist_df()
            last_updates_1h = (datetime.now(ZoneInfo("Europe/Moscow")) - hour_1_df[-1]['bucket'][0]).seconds
        
        if last_updates_1h > 3665: # 1 час 1 минута 5 секунд
            hour_4_df, hour_1_df = get_hist_df()
        
        # --- Текущие цены ---
        current_data = redis_orderbooks.get_orderbooks(1)
        if current_data.is_empty():
            print(f'{ct} current data is empty!')
            sleep(5)
            continue
        
        current_data = current_data.with_columns(
                ((pl.col('bidprice_0') + pl.col('askprice_0')) / 2.0).alias('avg_price')
            ).drop('exchange', 'market_type')
        
        # --- Обрабатываем каждую пару токенов ---
        for _, t1_name, t2_name, tf, wind, low_in, high_in, low_out, high_out in sorted_params:
            token_1 = t1_name + '_USDT'
            token_2 = t2_name + '_USDT'

            # --- Получаем информацию о кол-ве знаков после запятой в цене токена для округления цен ---
            dp_1 = coin_information['bybit_linear'][token_1]['price_scale']
            dp_2 = coin_information['bybit_linear'][token_2]['price_scale']
            
            # --- Обновляем открытые пары и текущие ордеры
            pending_orders = redis_orders.get_pending_orders()
            current_orders = postgre_manager.get_table('current_orders', df_type='polars')
            curr_orders_list = current_orders['token'].to_list()
            pairs = postgre_manager.get_table('pairs', df_type='polars')
        
            # --- Получаем средние цены за исторический период ---
            hist_df = hour_1_df if tf == '1h' else hour_4_df
            token_1_hist_price = hist_df.filter(pl.col('token') == token_1).tail(2 * wind)['avg_price']
            token_2_hist_price = hist_df.filter(pl.col('token') == token_2).tail(2 * wind)['avg_price']
            
            # --- Получаем текущие цены ---
            t1_curr_data = current_data.filter(pl.col('symbol') == token_1)
            t2_curr_data = current_data.filter(pl.col('symbol') == token_2)
        
            # --- Проверка на актуальность текущих цен ---
            t1_ts = t1_curr_data['ts'].item()
            t2_ts = t2_curr_data['ts'].item()
            
            if abs(t1_ts - t2_ts) > 5: # Если разница во времени между двумя ценами больше 5 секунд, пропускаем эту пару
                continue

            # Вместо текущей цены подставляем в функцию для расчёта z_score медианную цену за 5 секунд, чтобы избежать выбросов
            end_t = datetime.now().replace(tzinfo=ZoneInfo("Europe/Moscow"))
            st_t = end_t - timedelta(seconds = 5)
            
            t1_df_sec = postgre_manager.get_raw_orderbooks(exchange='bybit', market_type='linear', 
                            token=token_1, start_time=st_t).with_columns(
                            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
                        ).filter(
                (pl.col('bid_size') * pl.col('bid_price') > min_order) & 
                (pl.col('ask_size') * pl.col('ask_price') > min_order)
            )
            t2_df_sec = postgre_manager.get_raw_orderbooks(exchange='bybit', market_type='linear', 
                            token=token_2, start_time=st_t).with_columns(
                            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
                        ).filter(
                (pl.col('bid_size') * pl.col('bid_price') > min_order) & 
                (pl.col('ask_size') * pl.col('ask_price') > min_order)
            )

            if t1_df_sec.height >= 3 and t2_df_sec.height >= 3:
                t1_med_price = t1_df_sec['avg_price'].median()
                t2_med_price = t2_df_sec['avg_price'].median()
            else:
                continue
            
            t1 = token_1_hist_price.append(pl.Series("avg_price", [t1_med_price])).to_numpy()
            t2 = token_2_hist_price.append(pl.Series("avg_price", [t2_med_price])).to_numpy()
        
            alpha, beta, zscore = get_lr_zscore(t1, t2, np.array([wind]))
            
            # Добавляем z_score в массив для построения графика реального z_score
            z_score_buffer.append({'time': ct, 'token_1': token_1, 'token_2': token_2, 'z_score': zscore})
        
            try:
                t1_usdt_amount = check_open_conditions(token_1, current_orders, pending_orders, min_order, max_position)
                t2_usdt_amount = check_open_conditions(token_2, current_orders, pending_orders, min_order, max_position)
            except KeyError: # Данные в pending_orders не успели обновиться
                continue
        
            # ----- Проверяем условия для входа в позицию -----
            if t1_usdt_amount and t2_usdt_amount:
                t1_min_qty_step = get_step_info(coin_information, token_1, 'bybit_linear', 'bybit_linear')
                t1_price_tick = get_price_scale(coin_information, token_1, 'bybit_linear')
                t2_min_qty_step = get_step_info(coin_information, token_2, 'bybit_linear', 'bybit_linear')
                t2_price_tick = get_price_scale(coin_information, token_2, 'bybit_linear')
        
                usdt_amount_to_order = min(t1_usdt_amount, t2_usdt_amount) # Сколько ещё я могу загрузить в позицию
        
                # Проверяем открытие long-позиции по token_1 и short-позиции по token_2
                if zscore < low_in:
                    long_price = t1_curr_data['askprice_0'][0]
                    long_volume = t1_curr_data['askvolume_0'][0]
                    short_price = t2_curr_data['bidprice_0'][0]
                    short_volume = t2_curr_data['bidvolume_0'][0]
        
                    long_volume_usdt = long_volume / long_price
                    short_volume_usdt = short_volume / short_price
                    avail_usdt_amount = min(long_volume_usdt, short_volume_usdt, usdt_amount_to_order) # Доступный на бирже объём в usdt
                    
                    if avail_usdt_amount > min_order:
                        qty_1 = round_down(leverage * avail_usdt_amount / (1.0 + 2.0 * fee_rate) / long_price, t1_min_qty_step)
                        qty_2 = round_down(leverage * avail_usdt_amount / (1.0 + 2.0 * fee_rate) / short_price, t2_min_qty_step)
                        postgre_manager.add_pair_order(token_1=token_1, token_2=token_2, side='long', qty_1=qty_1, qty_2=qty_2)
                        redis_orders.add_order(exchange='bybit', token=token_1, qty=qty_1, price=long_price, side='long', 
                                               leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, status='created')
                        redis_orders.add_order(exchange='bybit', token=token_2, qty=qty_2, price=short_price, side='short', 
                                               leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')
                        
                        print(f'{ct} [Long open] Buy {qty_1} {token_1[:-5]} for {long_price}; sell {qty_2} {token_2[:-5]} for {short_price}; z_score: {zscore[0]:.2f}')
                        if with_break:
                            break_flag = True
                            break
                        # print(f'Текущие цены. [Long] ask: {t1_curr_data['askprice_0'][0]}, bid: {t1_curr_data['bidprice_0'][0]}; [Short] ask: {t2_curr_data['askprice_0'][0]}, bid: {t2_curr_data['bidprice_0'][0]}')
                # Проверяем открытие short-позиции по token_1 и long-позиции по token_2
                if zscore > high_in:
                    long_price = t2_curr_data['askprice_0'][0]
                    long_volume = t2_curr_data['askvolume_0'][0]
                    short_price = t1_curr_data['bidprice_0'][0]
                    short_volume = t1_curr_data['bidvolume_0'][0]
        
                    long_volume_usdt = long_volume / long_price
                    short_volume_usdt = short_volume / short_price
                    avail_usdt_amount = min(long_volume_usdt, short_volume_usdt, usdt_amount_to_order) / leverage # Доступный на бирже объём в usdt
                    
                    if avail_usdt_amount > min_order:
                        qty_1 = round_down(leverage * avail_usdt_amount / (1.0 + 2.0 * fee_rate) / short_price, t1_min_qty_step)
                        qty_2 = round_down(leverage * avail_usdt_amount / (1.0 + 2.0 * fee_rate) / long_price, t2_min_qty_step)
                        postgre_manager.add_pair_order(token_1=token_1, token_2=token_2, side='short', qty_1=qty_1, qty_2=qty_2)
                        redis_orders.add_order(exchange='bybit', token=token_1, qty=qty_1, side='short', 
                                               leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, price=short_price, status='created')
                        redis_orders.add_order(exchange='bybit', token=token_2, qty=qty_2, price=long_price, side='long', 
                                               leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')
                       
                        print(f'{ct} [Short open] Sell {qty_1} {token_1[:-5]} for {short_price}; Buy {qty_2} {token_2[:-5]} for {long_price}; z_score: {zscore[0]:.2f}')
                        if with_break:
                            break_flag = True
                            break
                        # print(f'Текущие цены. [Long] ask: {t1_curr_data['askprice_0'][0]}, bid: {t1_curr_data['bidprice_0'][0]}; [Short] ask: {t2_curr_data['askprice_0'][0]}, bid: {t2_curr_data['bidprice_0'][0]}')

            
            # ----- Проверяем условия выхода из позиции -----
            first_leg = current_orders.filter(pl.col('token') == token_1)
            second_leg = current_orders.filter(pl.col('token') == token_2)
            if first_leg.is_empty() or second_leg.is_empty(): # Если данные не успели обновиться
                continue
            
            long_opened =  pairs.filter((pl.col('token_1') == token_1) & (pl.col('token_2') == token_2) & (pl.col('side') == 'long')).height == 1
            short_opened =  pairs.filter((pl.col('token_1') == token_1) & (pl.col('token_2') == token_2) & (pl.col('side') == 'short')).height == 1
            
            if zscore > high_out and long_opened:
                long_price = t1_curr_data['bidprice_0'][0]
                long_volume = t1_curr_data['bidvolume_0'][0]
                short_price = t2_curr_data['askprice_0'][0]
                short_volume = t2_curr_data['askvolume_0'][0]
        
                open_qty_1 = float(first_leg['qty'].item())
                open_qty_2 = float(second_leg['qty'].item())
        
                long_exit_volume_usdt = long_volume * long_price
                short_exit_volume_usdt = short_volume * short_price
                avail_exit_usdt_amount = min(long_exit_volume_usdt, short_exit_volume_usdt) / leverage
                
                if long_volume > open_qty_1 and short_volume > open_qty_2:
                    print(f'{ct} [Long closed] Sell {open_qty_1} {token_1[:-5]} for {long_price}; Buy {open_qty_2} {token_2[:-5]} for {short_price}; z_score: {zscore[0]:.2f}')
                    # print(f'Текущие цены. [Long] ask: {t1_curr_data['askprice_0'][0]}, bid: {t1_curr_data['bidprice_0'][0]}; [Short] ask: {t2_curr_data['askprice_0'][0]}, bid: {t2_curr_data['bidprice_0'][0]}')

                    postgre_manager.delete_pair_order(token_1=token_1, token_2=token_2)
                    redis_orders.add_order(exchange='bybit', token=token_1, qty=open_qty_1, side='short', 
                                           leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, price=long_price, status='created')
                    redis_orders.add_order(exchange='bybit', token=token_2, qty=open_qty_2, price=short_price, side='long', 
                                           leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')
                    
                elif avail_exit_usdt_amount > min_order:
                    # print('Выходим из лонга частично', token_1, token_2, low_out, high_out, zscore)
                    pass
        
            if zscore < low_out and short_opened:
                long_price = t1_curr_data['askprice_0'][0]
                long_volume = t1_curr_data['askvolume_0'][0]
                short_price = t2_curr_data['bidprice_0'][0]
                short_volume = t2_curr_data['bidvolume_0'][0]
        
                open_qty_1 = float(first_leg['qty'].item())
                open_qty_2 = float(second_leg['qty'].item())
                
                if long_volume > open_qty_1 and short_volume > open_qty_2:
                    print(f'{ct} [Short closed] Buy {open_qty_1} {token_1[:-5]} for {long_price}; Sell {open_qty_2} {token_2[:-5]} for {short_price}; z_score: {zscore[0]:.2f}')
                    # print(f'Текущие цены. [Long] ask: {t1_curr_data['askprice_0'][0]}, bid: {t1_curr_data['bidprice_0'][0]}; [Short] ask: {t2_curr_data['askprice_0'][0]}, bid: {t2_curr_data['bidprice_0'][0]}')

                    postgre_manager.delete_pair_order(token_1=token_1, token_2=token_2)
                    redis_orders.add_order(exchange='bybit', token=token_1, qty=open_qty_1, side='long', 
                                           leverage=leverage, ord_id=str(uuid4()), ts=ts, price=long_price, status='created')
                    redis_orders.add_order(exchange='bybit', token=token_2, qty=open_qty_2, price=short_price, side='short', 
                                           leverage=leverage, ord_id=str(uuid4()), ts=ts, status='created')
        
                else:
                    # print('Выходим из шорта частично', token_1, token_2, low_out, high_out, zscore)
                    pass
        if break_flag:
            break
        
        if len(z_score_buffer) > 5_000:
            z_score_df = z_score_df.vstack(pl.DataFrame(z_score_buffer))
            z_score_df.write_parquet('./data/z_score_df.parquet')
            z_score_buffer = []
        
        sleep(0.5)
        
    
    
    except KeyboardInterrupt:
        print('Завершение работы.')
        # postgre_manager.close()
        break
    # except Exception as err:
    #     time_now = datetime.now()
    #     ct = time_now.strftime('%Y-%m-%d %H:%M:%S')
    #     print(f'{ct}: {err}')

2025-09-09 04:09:20 [Long closed] Sell 1456.0 ONT for 0.1382; Buy 1565.6 STRK for 0.1298; z_score: 1.04
2025-09-09 04:09:41 [Long closed] Sell 2204.3 GRT for 0.09334; Buy 8201.0 VET for 0.02436; z_score: 2.26
2025-09-09 04:17:56 [Long open] Buy 492.6 FLOW for 0.4055; sell 1165.5 STG for 0.1714; z_score: -2.06
2025-09-09 04:18:13 [Long open] Buy 664.6 CELO for 0.3006; sell 2144.7 GRT for 0.09315; z_score: -2.03
2025-09-09 04:39:24 [Long open] Buy 267.1 OP for 0.7479; sell 288.9 SNX for 0.6914; z_score: -2.05
2025-09-09 04:55:46 [Long open] Buy 1048.7 IOTA for 0.1905; sell 213.0 ONDO for 0.9354; z_score: -2.02
2025-09-09 05:00:08 [Long open] Buy 11814.0 GALA for 0.01691; sell 4054.0 XAI for 0.04927; z_score: -2.05

In [ ]:
# 2025-09-08 22:34:47 [Long open] Buy 215.0 ONDO for 0.927; sell 67.0 XRP for 2.9707; z_score: -2.00
# 2025-09-08 23:07:13 [Long open] Buy 382.2 CELO for 0.2972; sell 210.5 IMX for 0.5396; z_score: -2.00
# 2025-09-08 23:37:40 [Long open] Buy 2204.3 GRT for 0.09063; sell 8201.0 VET for 0.02436; z_score: -2.02
# 2025-09-09 00:38:54 [Long closed] Sell 382.2 CELO for 0.2988; Buy 210.5 IMX for 0.539; z_score: 0.71

In [51]:
# token_1 = 'IOTA_USDT'
# token_2 = 'SAND_USDT'
# qty_1 = 2204.3
# qty_2 = 8201.0
# side = 'long'


# postgre_manager.add_pair_order(token_1=token_1, token_2=token_2, side=side, qty_1=qty_1, qty_2=qty_2)
# postgre_manager.delete_pair_order(token_1=token_1, token_2=token_2)

# redis_orders.add_order(exchange='bybit', token=token_1, qty=open_qty_1, side='short', 
#                        leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, price=short_price, status='created')
# redis_orders.add_order(exchange='bybit', token=token_2, qty=open_qty_2, price=long_price, side='long', 
#                        leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')

In [52]:
pairs = postgre_manager.get_table('pairs', df_type='polars')
pairs

shape: (3, 5)
┌──────────┬───────────┬──────┬───────────────┬───────────────┐
│ token_1  ┆ token_2   ┆ side ┆ qty_1         ┆ qty_2         │
│ ---      ┆ ---       ┆ ---  ┆ ---           ┆ ---           │
│ str      ┆ str       ┆ str  ┆ decimal[*,8]  ┆ decimal[*,8]  │
╞══════════╪═══════════╪══════╪═══════════════╪═══════════════╡
│ ONT_USDT ┆ STRK_USDT ┆ long ┆ 1456.00000000 ┆ 1565.60000000 │
│ IMX_USDT ┆ NEAR_USDT ┆ long ┆ 370.60000000  ┆ 77.40000000   │
│ GRT_USDT ┆ VET_USDT  ┆ long ┆ 2204.30000000 ┆ 8201.00000000 │
└──────────┴───────────┴──────┴───────────────┴───────────────┘

In [27]:
current_orders = postgre_manager.get_table('current_orders', df_type='polars')
current_orders

shape: (6, 11)
┌───────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ token     ┆ exchange ┆ market_typ ┆ order_typ ┆ … ┆ usdt_amou ┆ realized_ ┆ leverage ┆ created_a │
│ ---       ┆ ---      ┆ e          ┆ e         ┆   ┆ nt        ┆ pnl       ┆ ---      ┆ t         │
│ str       ┆ str      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│           ┆          ┆ str        ┆ str       ┆   ┆ f64       ┆ f64       ┆          ┆ datetime[ │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ μs, Europ │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ e/Moscow] │
╞═══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ STRK_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.05009 ┆ -0.109874 ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆ 1         ┆           ┆          ┆ 8         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 21:41:12  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ ONT_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.863695 ┆ -0.10979  ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 8         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 21:41:13  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ VET_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.09406 ┆ -0.109922 ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆ 8         ┆           ┆          ┆ 8         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 23:37:41  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ GRT_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.931765 ┆ -0.109865 ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 8         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 23:37:42  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ NEAR_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.933218 ┆ -0.109745 ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 9         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 00:38:56  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ IMX_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.876012 ┆ -0.109803 ┆ 2.0      ┆ 2025-09-0 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 9         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 00:38:57  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
└───────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [53]:
pending_orders = redis_orders.get_pending_orders()
pending_orders

{}

In [29]:
trading_history = postgre_manager.get_table('trading_history')
trading_history

,token,exchange,market_type,order_type,order_side,open_price,close_price,open_usdt_amount,close_usdt_amount,qty,realized_pnl,leverage,created_at,closed_at,profit
id,,,,,,,,,,,,,,,
1,CELO_USDT,bybit,linear,market,buy,0.2971,0.2988,56.807037,57.1007,382.2,-0.125264,2.0,2025-09-08 23:07:14+03:00,2025-09-09 00:38:55+03:00,None
2,IMX_USDT,bybit,linear,market,sell,0.5398,0.5387,56.907693,56.6982,210.5,-0.124863,2.0,2025-09-08 23:07:14+03:00,2025-09-09 00:38:56+03:00,None
3,ONDO_USDT,bybit,linear,market,buy,0.9269,0.9330,99.696553,100.2975,215.0,-0.219933,2.0,2025-09-08 22:34:48+03:00,2025-09-09 00:42:01+03:00,None
4,XRP_USDT,bybit,linear,market,sell,2.9708,2.9707,99.686011,99.5185,67.0,-0.218944,2.0,2025-09-08 22:34:48+03:00,2025-09-09 00:42:02+03:00,None

In [30]:
trading_history['profit'].sum()

0

In [ ]:
# postgre_manager.delete_order('ONDO_USDT', 'bybit', 'linear')

In [36]:
redis_orders.clear_orders_table()

In [ ]:
postgre_manager.clear_table('current_orders')

In [ ]:
postgre_manager.clear_table('pairs')

In [ ]:
postgre_manager.clear_table('trading_history')

#### Open arbitrage orders

In [ ]:
logger.info('Запускаем основной цикл программы...')

arbitrage_tokens = {# 'ADA_USDT': {'long_exc': 'bybit', 'short_exc': 'okx', 'min_edge': 0.06},
                    # 'ALGO_USDT': {'long_exc': 'gate', 'short_exc': 'bybit', 'min_edge': -0.017}
                    'ADA_USDT': {'long_exc': 'gate', 'short_exc': 'bybit', 'min_edge': -10.017}
                   }

exit_flag = False
signal.signal(signal.SIGINT, signal_handler)
# ====================================
# Параметры запуска
limit_type = 'limit' # Первый ордер ставим по лучшей цене, а второй отправляем сразу же, как сматчился первый
n_ticks = Decimal('1')

demo = True
leverage = 2
max_usdt_order = 100
min_usdt_order = 10

max_orders = 3
# ====================================
# Основной цикл
while not exit_flag:
    token, data = None, None
    open_exc, cntr_side, cntr_qty = None, None, None
    long_exc, short_exc, min_edge = None, None, 512

    current_orders = postgre_manager.get_table('current_orders')
    n_current_orders = len(current_orders) // 2
    pending_orders = redis_order_manager.get_pending_orders()
    
    try:
        # Скачиваем текущие данные по ордербукам из Redis
        try:
            current_data = redis_price_manager.get_orderbooks(n_levels=5).filter(pl.col('symbol').is_in(arbitrage_tokens))
        except pl.exceptions.ColumnNotFoundError:
            sleep(1)
            continue

        # Проверка на то, что данные являются актуальными, что ни одна из бирж не подвисла
        if not is_data_up_to_date(current_data, time_thresh=10):
            logger.error(f'Устаревшие данные по ценам.')
            sleep(1)
        if len(current_data) == 0:
            raise Exception('No data!')
        
        for token, data in arbitrage_tokens.items():
            # Настройки направления сделок:
            long_exc = data['long_exc']
            short_exc = data['short_exc']
            min_edge = data['min_edge']

            # Определяем текущие цены
            df_long = current_data.filter((pl.col("exchange") == long_exc) & (pl.col("symbol") == token))
            df_short = current_data.filter((pl.col("exchange") == short_exc) & (pl.col("symbol") == token))
            long_price = df_long.select('askprice_0').item()
            short_price = df_short.select('bidprice_0').item()
            diff = (short_price / long_price - 1) * 100

            # Обработчик открытых в одном направлении лимитных ордеров.
            # ---------------------------------------------------------
            try:
                open_exc, cntr_side, cntr_qty = check_counter_conditions(token, pending_orders, long_exc, short_exc, long_price, short_price)
                cntr_qty = Decimal(cntr_qty)
                
                if open_exc == long_exc:
                    cntr_exc = short_exc
                elif open_exc == short_exc:
                    cntr_exc = long_exc
                
                cntr_ts = int(datetime.timestamp(datetime.now()))
                exc_name = cntr_exc + '_linear'

                resp = place_market_order(demo, exc_name, token, cntr_side, cntr_qty, coin_information)
                logger.info(f'[PLACE OPEN ORDER] {cntr_qty} {token}; {cntr_side} on {cntr_exc}')

                if cntr_exc == 'gate':
                    ord_id = resp['id']
                else:
                    ord_id = resp

                redis_order_manager.add_order(cntr_exc, token, float(cntr_qty), cntr_side, ord_id, cntr_ts, status='placed')
            
            except ValueError:
                pass                
            
            # Обработчик новых ордеров
            # -----------------------------------------------------------------------------            
            usdt_amount = check_open_conditions(token, current_orders, pending_orders, min_usdt_order, max_usdt_order)
            if usdt_amount:                
                long_exc_full = long_exc + '_linear'
                short_exc_full = short_exc + '_linear'
                
                ct = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                min_qty_step = get_step_info(coin_information, token, long_exc_full, short_exc_full)
                
                vol = leverage * float(usdt_amount) / max(long_price, short_price)
                volume = round_volume(volume=vol, qty_step=min_qty_step) 
                                
                usdt_amount = volume / Decimal(volume) * Decimal(max_usdt_order)

                # Сначала на обеих биржах меняем плечо, чтобы если есть проблемы со связью,
                #   всё отвалилось на этапе изменения плеча, а не после простановки ордера на первой бирже
                if token not in leverage_change_history:
                    set_leverage(demo=demo, exc=long_exc_full, symbol=token, leverage=leverage)
                    set_leverage(demo=demo, exc=short_exc_full, symbol=token, leverage=leverage)
                    logger.info(f'Leverage changing...')
    
                    leverage_change_history.append(token)
                    continue
                                                    
                
                if arbitrage_tokens[token]['long_exc'] == 'bybit':
                    first_order_exc = long_exc
                    side = 'buy'
                    price = long_price
                elif arbitrage_tokens[token]['short_exc'] == 'bybit':
                    first_order_exc = short_exc
                    side = 'sell'
                    price = short_price
                else:
                    first_order_exc = long_exc
                    side = 'buy'
                    price = long_price


                price_tick = get_price_scale(coin_information, token, first_order_exc + '_linear')
                if limit_type == 'instant':
                    l_price = Decimal(long_price) + n_ticks * price_tick
                    s_price = Decimal(short_price) - n_ticks * price_tick
                elif limit_type == 'limit':
                    l_price = Decimal(long_price) - n_ticks * price_tick
                    s_price = Decimal(short_price) + n_ticks * price_tick
                else:
                    raise NotImplementedError('Укажите корректный тип лимитного ордера!')

                l_price = l_price.normalize()
                s_price = s_price.normalize()

                price = l_price if first_order_exc == long_exc else s_price
                
                limit_diff = (s_price / l_price - 1) * 100

                
                logger.info(f'[PLACE OPEN ORDER] {volume} {token}; {side} on {first_order_exc}; {usdt_amount=:.2f}')
                logger.info(f'Current: long {long_price}, short {short_price}. Limit: long {l_price}, short {s_price}; diff: {diff:.3f}; limit diff: {limit_diff:.3f}; ')
        
                ts = int(datetime.timestamp(datetime.now()))
                
                resp = place_limit_order(demo=demo, 
                                exc=first_order_exc + '_linear', 
                                symbol=token, 
                                side=side, 
                                volume=volume, 
                                price=price,
                                coin_information=coin_information)
                
                if first_order_exc == 'gate':
                    ord_id = resp['id']
                else:
                    ord_id = resp
                
                redis_order_manager.add_order(exchange=first_order_exc, 
                                              token=token, 
                                              qty=float(volume), 
                                              side=side, 
                                              ord_id=ord_id, 
                                              ts=ts, 
                                              status='placed')
        
        sleep(0.05)

    except (KeyboardInterrupt, CancelledError):
        print('Завершение работы.')
        break

In [ ]:
handle_position(demo, exc='bybit_linear',
                symbol='ADA_USDT',
                order_type='limit',
                coin_information=coin_information)

In [ ]:
token

In [ ]:
pending_orders = redis_order_manager.get_pending_orders()
current_orders = postgre_manager.get_table('current_orders')
current_orders

In [ ]:
pending_orders

In [ ]:
redis_order_manager.add_order(exchange=first_order_exc, 
                                              token=token, 
                                              qty=float(volume), 
                                              side=side, 
                                              ord_id=ord_id, 
                                              ts=ts, 
                                              status='placed')

In [ ]:
redis_order_manager.delete_order(exchange='okx', token='ADA_USDT')

In [ ]:
redis_order_manager.clear_orders_table()

In [ ]:
# План
# 3. Добавить выскакивающее предупреждение, если по какому-то токену идёт большое отклонение на разных биржах, пригодное для арбитража.
# 4. Добавить автоматический стоп-лосс для шортовой сделки и take-profit для лонга
# 7. Можно попробовать реализовать выход из сделок по фандингу, ставя лимитный ордер на 1 - 1.5% от текущей цены - 
# при выплате фандинга цена резко просаживается, а где-то через минуту возвращается обратно. Можно попробовать это использовать.

# Надо посмотреть, считаются ли fees при учёте usdt_amount. Кажется, что у ByBit комиссия уже включена в usdt_amount,
# а у OKX - нет. _order_handler() и _position_handler() OKX usdt_amount считается как qty * price, так что fees не учитываются.

# To do:
# 3. Настроить нормальное логгирование. Продумать те статы, которые мне нужны на экране для анализа.
# 4. Настроить автоматическое обновление статов каждые 10 - 30 минут
# 5. Написать функцию для проверки открытых позиций на бирже и синхронизации с таблицей current_orders в БД.
# 6. Написать функцию, которая будет искать токены с максимальным отклонением от mean значения в текущий момент.

#### Manual open

In [ ]:
redis_order_manager = RedisManager(db_name = 'orders')

In [ ]:
demo = True
token = 'STRK_USDT'
side = 'buy'
usdt_amount = 20
leverage = 2
n_ticks = 2
stop_loss = 0.125

exc = 'bybit'
exc_full = f'{exc}_linear'

dp = coin_information[exc_full][token]['min_qty']

In [ ]:
current_data = redis_price_manager.get_orderbooks(n_levels=1).filter(pl.col('symbol') == token)
if len(current_data) == 0:
    raise Exception('No data!')

set_leverage(demo=demo, exc=exc_full, symbol=token, leverage=leverage)
logger.info(f'Leverage changing...')

In [ ]:
# Открываем лонг-ордер, тип заявки - лимитка на n_ticks лучше текущей цены.
current_data = redis_price_manager.get_orderbooks(n_levels=1).filter(pl.col('symbol') == token)
price = current_data.select(pl.when(side == 'buy').then(pl.col("askprice_0")).otherwise(pl.col("bidprice_0"))).item()
volume = round_size(leverage * usdt_amount / price, dp)

if not is_data_up_to_date(current_data, time_thresh=10):
    logger.error(f'Устаревшие данные по ценам.')
    raise Exception(f'Устаревшие данные по ценам.')
if len(current_data) == 0:
    logger.error(f'No data!')
    raise Exception(f'No data!')

dp = int(coin_information[exc_full][token]['price_scale'])
price_tick = get_price_scale(coin_information, token, exc_full)

# Выбираем цену для установки лимитного ордера на n_ticks тиков лучше текущей цены
if side == 'buy':
    curr_price = current_data.filter((pl.col('exchange') == exc)).select('askprice_0').item()
    price = curr_price - n_ticks * price_tick
    stop_loss = round(price / 2, dp)
elif side == 'sell':
    curr_price = current_data.filter((pl.col('exchange') == exc)).select('bidprice_0').item()
    price = curr_price + n_ticks * price_tick
    stop_loss = round(price * Decimal('1.8'), dp)

ord_id = place_market_order(demo=demo,
                            exc=exc_full,
                            symbol=token,
                            side=side,
                            volume=volume,
                            coin_information=coin_information,
                            stop_loss=stop_loss)
if ord_id:
    if exc == 'gate':
        ord_id = ord_id['id']
    ts = int(datetime.timestamp(datetime.now()))
    redis_order_manager.add_order(exchange=exc, 
                                  token=token, 
                                  qty=volume, 
                                  side=side,
                                  ord_id=ord_id,
                                  ts=ts,
                                  status='placed')

In [ ]:
if exc == 'gate':
    ord_id = ord_id['id']

cancel_id = cancel_order(demo=demo, exc=exc_full, symbol=token, order_id=ord_id)
if cancel_id:
    redis_order_manager.delete_order(exchange=exc, token=token)

In [ ]:
handle_position(demo=demo, exc=exc_full, symbol=token, order_type='market', coin_information=coin_information)

#### Вход в арбитражную сделку:

In [ ]:
"""
logger.info('Запускаем основной цикл программы...')
exc_list = ['bybit', 'okx', 'gate']
mt_list = ['linear', 'spot']

exit_flag = False
signal.signal(signal.SIGINT, signal_handler)
# ====================================
# Параметры запуска
max_mean = 1.2 # Максимальное значение mean в процентах, выше которого все крипто-пары отсекаются
min_std = 0.12 # Показатель std из stats_df для конкретной монеты
std_coef = 2.8 # На сколько умножаем std, вычисляя макс. расстояния от среднего значения
min_edge = 0.0
min_dist = 0.4

demo = False
leverage = 1
max_usdt_order = 20
min_usdt_order = 5

max_orders = 3

bybit_trade = BybitTrade(demo=demo)
okx_trade = OkxTrade(demo=demo)
gate_client = GateTrade(demo=demo)
trading_clients = {'bybit': bybit_trade, 'okx': okx_trade, 'gate': gate_client}

# ====================================
# Основной цикл
while not exit_flag:
    token, data = None, None
    df_in = pd.DataFrame()
    token_dict = dict()
    syms = []

    current_orders = postgre_manager.get_table('current_orders')
    n_current_orders = len(current_orders) // 2
    
    try:
        # Скачиваем текущие данные по ордербукам из Redis
        try:
            current_data = redis_manager.get_orderbooks(n_levels=5)
        except pl.exceptions.ColumnNotFoundError:
            sleep(1)
            continue

        # Проверка на то, что данные являются актуальными, что ни одна из бирж не подвисла
        sorted_df = current_data.sort(by='ts')
        oldest_ts_exc = sorted_df.select("exchange").head(1).item()
        last_entry = sorted_df.filter(pl.col('exchange') == oldest_ts_exc).select("ts").tail(1).item()
        time_delta = int(datetime.timestamp(datetime.now())) - last_entry
        
        # Если данные на бирже последний раз обновлялись больше 20 секунд назад, прерываем работу программы
        if time_delta > 10:
            logger.error(f'Отсутствует соединение с биржей {oldest_ts_exc}.')
            sleep(5)
            continue

        # Здесь будет обработчик текущих лимитных ордеров.
        # Args: order_price, order_side, order_time
        # Если цена, полученная через Redis, доходит до цены ордера - отправляем запрос на подтверждение ордера.
        # Если всё норм и ордер сматчился - отправляем лимитку в обратную сторону.
        # Если прошло 10-15-20 секунд и ордер не выкупили (а цена уехала), отменяем ордер
        # После всех манипуляций возвращаем переменные и order_status в исходное состояние.
        
        # Продолжаем, если данные обновляются регулярно
        stats_data = postgre_manager.get_table('stats_data')
        stats_data = pl.from_pandas(stats_data)
        df_in = find_tokens_to_open_order(current_data=current_data, 
                                          stats_data=stats_data, 
                                          max_mean=max_mean, 
                                          min_std=min_std, 
                                          std_coef=std_coef, 
                                          min_edge=min_edge,
                                          min_dist=min_dist)
        
        # Создадим словарь с токенами для того, чтобы посчитать, сколько usdt ещё доступно для открытия ордера.
        if not df_in.is_empty():
            # Если в df_in есть несколько вариантов для одного токена:
            n_counts = df_in["token"].value_counts(sort=True).select('count').head(1).item()
            if n_counts > 1:
                print('Есть несколько вариантов для одного токена')
                df_in_copy = df_in.clone()
                if bybit_diff - 0.1 < other_diff:
                    df_in = df_in.filter((pl.col("token") != token) | ((pl.col("long_exc") != "bybit") & (pl.col("short_exc") != "bybit")))
                else:
                    df_in = df_in.filter((pl.col("token") != token) | ((pl.col("long_exc") == "bybit") | (pl.col("short_exc") == "bybit")))
                
                exit_flag = True
                break
            
            token_list = df_in['token'].to_list()
                        
            for token in token_list:
                if token in current_orders['token'].to_list():
                    token_dict[token] = max_usdt_order - current_orders[current_orders['token'] == token].iloc[0]['usdt_amount']
                else:
                    token_dict[token] = max_usdt_order
        else:
            token_list = []

        for row in df_in.to_dicts():            
            token = row["token"]
            long_exc = row["long_exc"]
            short_exc = row["short_exc"]
                        
            if token_dict[token] < min_usdt_order:
                continue
            
            usdt_remain = 0 # Сбрасываем настройки для безопасности
            
            min_edge = row["thresh"]
            price_long = row['ask_long']
            price_short = row['bid_short']
            thresh = row['thresh']
        
            df_long = current_data.filter((pl.col("exchange") == long_exc) & (pl.col("symbol") == token))
            df_short = current_data.filter((pl.col("exchange") == short_exc) & (pl.col("symbol") == token))
            ask_price = df_long.select('askprice_0', 'askprice_1', 'askprice_2', 'askprice_3', 'askprice_4').row(0)
            ask_size = df_long.select('askvolume_0', 'askvolume_1', 'askvolume_2', 'askvolume_3', 'askvolume_4').row(0)
            bid_price = df_short.select('bidprice_0', 'bidprice_1', 'bidprice_2', 'bidprice_3', 'bidprice_4').row(0)
            bid_size = df_short.select('bidvolume_0', 'bidvolume_1', 'bidvolume_2', 'bidvolume_3', 'bidvolume_4').row(0)
            long_ob = [[price, size] for price, size in zip(ask_price, ask_size)]
            short_ob = [[price, size] for price, size in zip(bid_price, bid_size)]
            
            usdt_remain = token_dict[token]
            edge = max(thresh, min_edge)
            
            res = get_open_volume(long_orderbook=long_ob, 
                                  short_orderbook=short_ob, 
                                  min_edge=edge, 
                                  max_usdt=usdt_remain, # Умножаем на 2, чтобы был запас по ликвидности
                                  debug=False)
            
            # Если в ордербуке достаточно ликвидности для открытия ордера с заданным diff, открываем сделку
            # Проверяем, что у нас есть свободные слоты на открытие ордеров, или что ордер уже открыт и мы можем докупиться
            if res['usdt_amount'] >= min_usdt_order and (n_current_orders < max_orders or token in current_orders['token'].to_list()):
                # Если мне предлагают открыть ордер в направлении, отличном от уже существующего на бирже
                if token in current_orders['token'].to_list():
                    try:
                        long_position_side = current_orders[(current_orders['token'] == token) & 
                                                            (current_orders['exchange'] == long_exc)]['order_side'].item()
                        short_position_side = current_orders[(current_orders['token'] == token) & 
                                                            (current_orders['exchange'] == short_exc)]['order_side'].item()
    
                        if long_position_side == 'sell' or short_position_side == 'buy':
                            continue
                    except ValueError:
                        # Это означает, что мне предлагают открыть ещё одну сделку на другой бирже
                        continue
                
                
                long_exc_full = long_exc + '_linear'
                short_exc_full = short_exc + '_linear'
                
                ct = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                min_qty_step = get_step_info(coin_information, token, long_exc_full, short_exc_full)
                curr_diff = res['edge']
                volume = round_volume(volume=res['volume'], qty_step=min_qty_step) # Делим на 2, избавляясь от коэффа
                
                # Если при округлении цена упала меньше минимально возможной
                if volume < min_qty_step:
                    continue
                
                usdt_amount = volume / Decimal(res['volume']) * Decimal(res['usdt_amount'])
                mean = row['mean']
                std = row['std']
                deviation = (curr_diff - mean) / std

                long_price = long_ob[0][0]
                short_price = short_ob[0][0]
                
                # Сначала на обеих биржах меняем плечо, чтобы если есть проблемы со связью,
                #   всё отвалилось на этапе изменения плеча, а не после простановки ордера на первой бирже
                if token not in leverage_change_history:
                    set_leverage(demo=demo, exc=long_exc_full, symbol=token, leverage=leverage)
                    set_leverage(demo=demo, exc=short_exc_full, symbol=token, leverage=leverage)
                    logger.info(f'Leverage changing...')

                    leverage_change_history.append(token)
                    continue
                
                # Для дебага добавляем ордербук, на основании которого был открыт ордер, в список, хранящий историю
                orders_history.append({'time': ct, 'row': row, 'res': res, 'qty_step': min_qty_step})
                with open("./data/open_order_history.pkl", "wb") as f:
                    pickle.dump(orders_history, f)

                logger.info(f'[PLACE OPEN ORDER] {volume} {token}; diff: {curr_diff:.3f}, {thresh=:.3f}, {mean=:.3f}, {std=:.3f}; {deviation=:.3f}')
                logger.info(f'Цены во время простановки ордера. long: {price_long} ({long_exc}), short: {price_short} ({short_exc}); {usdt_amount=:.2f}')
                                    
                # Открываем лонг-ордер
                long_order_resp = place_market_order(demo=demo, exc=long_exc_full, symbol=token, side='buy', volume=volume)
                logger.info(f'Лонг ордер ({long_exc}) отправлен на биржу.')
                
                # Открываем шорт-ордер
                short_order_resp = place_market_order(demo=demo, exc=short_exc_full, symbol=token, side='sell', volume=volume)
                logger.info(f'Шорт ордер ({short_exc}) отправлен на биржу.')
                

                # Обрабатываем полученные ответы и заносим ордеры в БД
                handle_position(demo=demo, exc=long_exc_full, symbol=token, order_type='market')
                handle_position(demo=demo, exc=short_exc_full, symbol=token, order_type='market')
        
        sleep(0.02)
    except (KeyboardInterrupt, CancelledError):
        print('Завершение работы.')
        break
    # except RuntimeError as e:
    #     print(f"Ошибка выполнения: {e}")


"""