In [1]:
from jaref_bot.data.http_api import ExchangeManager, BybitRestAPI
from jaref_bot.utils.coins import get_step_info, get_price_scale
from jaref_bot.trading.functions import set_leverage

from jaref_bot.db.postgres_manager import DBManager
from jaref_bot.db.redis_manager import RedisManager
from jaref_bot.config.credentials import host, user, password, db_name

import pandas as pd
import polars as pl
import numpy as np
from datetime import datetime
from time import sleep, time
from decimal import Decimal, ROUND_DOWN
import pickle
import ast

from zoneinfo import ZoneInfo
from datetime import timedelta
from jaref_bot.utils.pair_trading import get_lr_zscore
from uuid import uuid4
import math
from functools import lru_cache

In [2]:
def round_down(value: float, dp: float):
    return round(math.floor(value / dp) * dp, 6)

In [3]:
def get_thresholds():
    data = []
    with open('d:/python/crypto/jaref_bot/config/thresholds.txt', 'r') as file:
        for line in file:
            line = line.strip()
            if line:
                tuple_data = ast.literal_eval(line)
                data.append(tuple_data)
    return data

In [4]:
def place_order(token_1, token_2, pos_side, qty_1, qty_2, t1_price, t2_price,
                t1_orig_side, t2_orig_side, ts, dp_1, dp_2, db_manager, redis_manager):
    if pos_side == 'open':
        db_manager.add_pair_order(token_1=token_1, token_2=token_2, side=t1_orig_side, qty_1=qty_1, qty_2=qty_2)
        redis_manager.add_order(exchange='bybit', token=token_1, qty=qty_1, side=t1_orig_side, price=t1_price,
                       leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, status='created')
        redis_manager.add_order(exchange='bybit', token=token_2, qty=qty_2, side=t2_orig_side, price=t2_price,
                       leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')

    elif pos_side == 'close':
        db_manager.delete_pair_order(token_1=token_1, token_2=token_2)
        redis_manager.add_order(exchange='bybit', token=token_1, qty=qty_1, side=t2_orig_side, price=t1_price,
                       leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, status='created')
        redis_manager.add_order(exchange='bybit', token=token_2, qty=qty_2, side=t1_orig_side, price=t2_price,
                       leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')
    else:
        raise Exception('Параметр pos_side может принимать значения только "open" или "close"')

In [5]:
def check_open_conditions(token: str,
                          current_orders: pd.DataFrame,
                          pending_orders: dict,
                          min_order: float,
                          max_position: float) -> float:
    """
        Функция проверяет условия для открытия нового ордера. Новый ордер будет открыт если:
        - Токена ещё нет ни в текущих ордерах, ни в открытых позициях
        - Токен есть в открытых позициях, но размер позиции позволяет открыть ещё одну сделку.

        Args:
            token - название токена. Например, 'ADA_USDT'.
            current_orders - датафрейм с текущими позициями.
            pending_orders - словарь с текущими ордерами.
            max_position - максимально возможный размер позиции на бирже.
        Return:
            Размер ордера в usdt, который можно открыть.

    """
    # Сначала проверяем условие, что такой ордер ещё не открывали
    token_in_positions = token in current_orders['token'].to_list()

    token_in_pending = False
    position_size = 0
    for exc, data in pending_orders.items():
        for tok in data:
            if tok == token:
                token_in_pending = True
                position_size += float(data[tok]['qty'])
    if not (token_in_positions or token_in_pending):
        return max_position

    # Проверяем условие, что ордер уже есть среди открытых позиций, но размер позиции позволяет добавить
    if token_in_positions:
        try:
            price = current_orders.filter(pl.col('token') == token)['price'].max()
            opened_position = current_orders.filter(pl.col('token') == token)['usdt_amount'].max()

            position_usdt = position_size * price + opened_position
            if position_usdt < max_position - min_order:
                return max_position - position_usdt
        except TypeError: # Ситуация, когда команда на закрытие позиции по этому токену уже отдана, но сам токен из БД ещё не убран
            return False


    return False

In [6]:
def change_position(token_1, token_2, pos_side, t1_orig_side, t2_orig_side, t1_data, t2_data, t1_usdt_amount, t2_usdt_amount,
                    leverage, min_order, fee_rate, ts, z_score, coin_information, db_manager, redis_manager):
    ct = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    t1_min_qty_step = get_step_info(coin_information, token_1, 'bybit_linear', 'bybit_linear')
    t2_min_qty_step = get_step_info(coin_information, token_2, 'bybit_linear', 'bybit_linear')

    dp_1 = coin_information['bybit_linear'][token_1]['price_scale']
    dp_2 = coin_information['bybit_linear'][token_2]['price_scale']

    if pos_side == 'open':
        t1_price = t1_data['askprice_0'][0] if t1_orig_side == 'long' else t1_data['bidprice_0'][0]
        t2_price = t2_data['bidprice_0'][0] if t1_orig_side == 'long' else t2_data['askprice_0'][0]
        t1_vol = t1_data['askvolume_0'][0] if t1_orig_side == 'long' else t1_data['bidvolume_0'][0]
        t2_vol = t2_data['bidvolume_0'][0] if t1_orig_side == 'long' else t2_data['askvolume_0'][0]

        t1_avail_usdt = t1_vol / t1_price
        t2_avail_usdt = t2_vol / t2_price

        avail_usdt = min(t1_avail_usdt, t2_avail_usdt, t1_usdt_amount, t2_usdt_amount) * leverage

        if avail_usdt > min_order:
            qty_1 = round_down(avail_usdt / (1.0 + 2.0 * fee_rate) / t1_price, t1_min_qty_step)
            qty_2 = round_down(avail_usdt / (1.0 + 2.0 * fee_rate) / t2_price, t2_min_qty_step)

            place_order(token_1=token_1, token_2=token_2, pos_side=pos_side, qty_1=qty_1, qty_2=qty_2,
                t1_price=t1_price, t2_price=t2_price, t1_orig_side=t1_orig_side, t2_orig_side=t2_orig_side,
                ts=ts, dp_1=dp_1, dp_2=dp_2, db_manager=db_manager, redis_manager=redis_manager)

            act_1 = 'Buy' if t1_orig_side == 'long' else 'Sell'
            act_2 = 'Sell' if t1_orig_side == 'long' else 'Buy'
            print(f'{ct} [{t1_orig_side.title()} open] {act_1} {qty_1} {token_1[:-5]} for {t1_price}; {act_2} {qty_2} {token_2[:-5]} for {t2_price}; z_score: {z_score:.2f}')

    elif pos_side == 'close':
        t1_price = t1_data['bidprice_0'][0] if t1_orig_side == 'long' else t1_data['askprice_0'][0]
        t2_price = t2_data['askprice_0'][0] if t1_orig_side == 'long' else t2_data['bidprice_0'][0]
        t1_vol = t1_data['bidvolume_0'][0] if t1_orig_side == 'long' else t1_data['askvolume_0'][0]
        t2_vol = t2_data['askvolume_0'][0] if t1_orig_side == 'long' else t2_data['bidvolume_0'][0]

        current_orders = db_manager.get_table('current_orders', df_type='polars')
        first_leg = current_orders.filter(pl.col('token') == token_1)
        second_leg = current_orders.filter(pl.col('token') == token_2)

        open_qty_1 = first_leg['qty'][0]
        open_qty_2 = second_leg['qty'][0]

        t1_avail_volume = t1_price * t1_vol
        t2_avail_volume = t2_price * t2_vol
        # avail_exit_usdt = min(t1_avail_volume, t2_avail_volume) / leverage

        if t1_vol > open_qty_1 and t2_vol > open_qty_2:
            # debug_arr.append({'token_1': token_1, 'token_2': token_2, 't1': t1, 't2': t2,
            #                   't1_med_price': t1_med_price, 't2_med_price': t2_med_price, 'zscore': zscore})

            db_manager.delete_pair_order(token_1, token_2)
            redis_manager.add_order(exchange='bybit', token=token_1, qty=open_qty_1, side=t2_orig_side,
                                   leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, price=t1_price, status='created')
            redis_manager.add_order(exchange='bybit', token=token_2, qty=open_qty_2, price=t2_price, side=t1_orig_side,
                                   leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')

            act_1 = 'Sell' if t1_orig_side == 'long' else 'Buy'
            act_2 = 'Buy' if t1_orig_side == 'long' else 'Sell'
            print(f'{ct} [{t1_orig_side.title()} closed] {act_1} {open_qty_1} {token_1[:-5]} for {t1_price}; {act_2} {open_qty_2} {token_2[:-5]} for {t2_price}; z_score: {z_score:.2f}')

In [7]:
def get_hist_df(postgre_manager, start_time):
    hour_1_df = postgre_manager.get_orderbooks(exchange='bybit',
                                             market_type='linear',
                                             interval='1h',
                                             start_date=start_time)
    cols_to_drop = ('exchange', 'market_type', 'bid_price', 'bid_size', 'ask_price', 'ask_size')
    hour_1_df = hour_1_df.with_columns(
            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
        )
    hour_1_df = hour_1_df.drop(cols_to_drop)

    hour_4_df = postgre_manager.get_orderbooks(exchange='bybit',
                                         market_type='linear',
                                         interval='4h',
                                         start_date=start_time)
    hour_4_df = hour_4_df.with_columns(
            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
        )
    hour_4_df = hour_4_df.drop(cols_to_drop)

    return hour_4_df, hour_1_df

In [8]:
def calculate_profit(open_price, close_price, n_coins=None, usdt_amount=None, side='long', fee_rate=0.00055):
    if n_coins is None:
        n_coins = round(usdt_amount / open_price)

    usdt_open = n_coins * open_price
    open_fee = usdt_open * fee_rate

    usdt_close = n_coins * close_price
    close_fee = usdt_close * fee_rate

    if side == 'long':
        profit = usdt_close - usdt_open - open_fee - close_fee
    elif side == 'short':
        profit = usdt_open - usdt_close - open_fee - close_fee
    return profit

In [9]:
@lru_cache
def set_leverage_cached(token, leverage):
    set_leverage(demo=demo, exc='bybit_linear', symbol=token + '_USDT', leverage=leverage)

In [24]:
demo = True
open_new_orders = True # Открывать новые позиции или только закрываем уже существующие
test_mode = True # Вместо реального открытия ордеров выводим сообщение на экран
update_lever = False

exchange = 'bybit'
min_order = 50     # Минимальный размер ордера
max_position = 100 # Максимальный размер одного плеча в парной позиции
max_pairs = 5      # Максимальное кол-во открытых позиций
leverage = 2       # Плечо
fee_rate = 0.00055 # Процент комиссии биржи
td = 120           # За сколько последних часов брать историю

In [25]:
update_positions_flag = False

print(f'{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} Начинаем работу...')

params = get_thresholds()
token_params = sorted(params, key=lambda x: x[0], reverse=True)

exc_manager = ExchangeManager()
exc_manager.add_market("bybit_linear", BybitRestAPI('linear'))

db_params = {'host': host, 'user': user, 'password': password, 'dbname': db_name}
postgre_manager = DBManager(db_params)
redis_orders = RedisManager(db_name = 'orders')
redis_orderbooks = RedisManager(db_name = 'orderbooks')

coin_information = exc_manager.get_instrument_data()

with open("./data/coin_information.pkl", "wb") as f:
    pickle.dump(coin_information, f)

end_time = datetime.now().replace(tzinfo=ZoneInfo("Europe/Moscow"))
start_time = end_time - timedelta(hours = td)

print(f'{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} Обновление плечей на бирже ByBit')
if update_lever:
    for _, t1_name, t2_name, tf, wind, thresh_in, thresh_out in token_params:
        set_leverage_cached(token=t1_name, leverage=leverage)
        set_leverage_cached(token=t2_name, leverage=leverage)

print(f'{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} Старт основного цикла.')
while True:
    try:
        zscore_arr = []

        time_now = datetime.now()
        ts = int(datetime.timestamp(time_now))
        ct = time_now.strftime('%Y-%m-%d %H:%M:%S')
        print(f'Текущее время: {ct}', end='\r')

        # --- Подгружаем исторические датафреймы 1 раз в час ---
        try:
            last_updates_1h = (datetime.now(ZoneInfo("Europe/Moscow")) - hour_1_df[-1]['bucket'][0]).seconds
        except NameError:
            hour_4_df, hour_1_df = get_hist_df(postgre_manager, start_time)
            last_updates_1h = (datetime.now(ZoneInfo("Europe/Moscow")) - hour_1_df[-1]['bucket'][0]).seconds

        if last_updates_1h > 3665: # 1 час 1 минута 5 секунд
            hour_4_df, hour_1_df = get_hist_df(postgre_manager, start_time)

            # Обновляем 1 раз в час пороги входа/выхода на случай, если они изменились
            params = get_thresholds()
            token_params = sorted(params, key=lambda x: x[0], reverse=True)

        # --- Текущие данные ---
        current_data = redis_orderbooks.get_orderbooks(1)
        if current_data.is_empty():
            print(f'{ct} current data is empty!')
            sleep(10)
            continue

        current_data = current_data.with_columns(
                ((pl.col('bidprice_0') + pl.col('askprice_0')) / 2.0).alias('avg_price')
            ).drop('exchange', 'market_type')

        pending_orders = redis_orders.get_pending_orders()
        current_orders = postgre_manager.get_table('current_orders', df_type='polars')
        pairs = postgre_manager.get_table('pairs', df_type='polars')

        # --- Секундный датафрейм для подсчёта среднего значения ---
        end_t = datetime.now().replace(tzinfo=ZoneInfo("Europe/Moscow"))
        st_t = end_t - timedelta(seconds = 6)

        df_sec = postgre_manager.get_raw_orderbooks(exchange='bybit', market_type='linear', start_time=st_t).with_columns(
            ((pl.col('bid_price') + pl.col('ask_price')) / 2.0).alias('avg_price')
        ).filter(
            (pl.col('bid_size') * pl.col('bid_price') > min_order) &
            (pl.col('ask_size') * pl.col('ask_price') > min_order)
        )

        # --- Обрабатываем каждую пару токенов ---
        for _, t1_name, t2_name, tf, wind, thresh_in, thresh_out in token_params:
            token_1 = t1_name + '_USDT'
            token_2 = t2_name + '_USDT'
            t1_med_price = None
            t2_med_price = None
            z_score = 0

            low_in = -2.0
            low_out = -0.5
            high_in = 2.0
            high_out = 0.5

            # --- Получаем информацию о кол-ве знаков после запятой в цене токена для округления цен ---
            # dp_1 = coin_information['bybit_linear'][token_1]['price_scale']
            # dp_2 = coin_information['bybit_linear'][token_2]['price_scale']

            # --- Обновляем открытые пары и текущие ордеры
            if update_positions_flag:
                pending_orders = redis_orders.get_pending_orders()
                current_orders = postgre_manager.get_table('current_orders', df_type='polars')
                pairs = postgre_manager.get_table('pairs', df_type='polars')
                update_positions_flag = False

            # --- Получаем средние цены за исторический период ---
            hist_df = hour_1_df if tf == '1h' else hour_4_df

            # Убираем последнее значение, которое постоянно обновляется
            token_1_hist_price = hist_df.filter(pl.col('token') == token_1).tail(2 * wind + 1)['avg_price'][:-1]
            token_2_hist_price = hist_df.filter(pl.col('token') == token_2).tail(2 * wind + 1)['avg_price'][:-1]

            # --- Получаем текущие цены ---
            t1_curr_data = current_data.filter(pl.col('symbol') == token_1)
            t2_curr_data = current_data.filter(pl.col('symbol') == token_2)

            # --- Проверка на актуальность текущих цен ---
            try:
                t1_ts = t1_curr_data['ts'].item()
                t2_ts = t2_curr_data['ts'].item()
            except ValueError: # Ситуация, когда после восстановления соединения не все токены успевают обновиться
                sleep(5)
                break

            if abs(t1_ts - t2_ts) > 10: # Если разница во времени между двумя ценами больше 10 секунд, пропускаем эту пару
                continue

            # Вместо текущей цены подставляем в функцию для расчёта z_score медианную цену за 5 секунд, чтобы избежать выбросов
            t1_df_sec = df_sec.filter(pl.col('token') == token_1)
            t2_df_sec = df_sec.filter(pl.col('token') == token_2)

            if t1_df_sec.height >= 3 and t2_df_sec.height >= 3:
                t1_med_price = t1_df_sec['avg_price'].median()
                t2_med_price = t2_df_sec['avg_price'].median()
                t1 = token_1_hist_price.append(pl.Series("avg_price", [t1_med_price])).to_numpy()
                t2 = token_2_hist_price.append(pl.Series("avg_price", [t2_med_price])).to_numpy()

                alpha, beta, zscore = get_lr_zscore(t1, t2, np.array([wind]))
                z_score = zscore[0]
            else:
                continue

            # ----- Проверяем условия для входа в позицию -----
            if open_new_orders and pairs.height < max_pairs:
                try:
                    t1_usdt_amount = check_open_conditions(token_1, current_orders, pending_orders, min_order, max_position)
                    t2_usdt_amount = check_open_conditions(token_2, current_orders, pending_orders, min_order, max_position)
                except KeyError: # Данные в pending_orders не успели обновиться
                    continue

                if t1_usdt_amount and t2_usdt_amount:
                    # Проверяем открытие long-позиции по token_1 и short-позиции по token_2
                    if zscore < low_in:
                        if not test_mode:
                            change_position(token_1, token_2, pos_side='open', t1_orig_side='long', t2_orig_side='short',
                                t1_data=t1_curr_data, t2_data=t2_curr_data, t1_usdt_amount=t1_usdt_amount,
                                t2_usdt_amount=t2_usdt_amount, leverage=leverage, min_order=min_order, fee_rate=fee_rate, ts=ts,
                                z_score=z_score, coin_information=coin_information,
                                db_manager=postgre_manager, redis_manager=redis_orders)
                        else:
                            print('Long opened')
                        update_positions_flag = True
                        break

                    # Проверяем открытие short-позиции по token_1 и long-позиции по token_2
                    if zscore > high_in:
                        if not test_mode:
                            change_position(token_1, token_2, pos_side='open', t1_orig_side='short', t2_orig_side='long',
                                t1_data=t1_curr_data, t2_data=t2_curr_data, t1_usdt_amount=t1_usdt_amount,
                                t2_usdt_amount=t2_usdt_amount, leverage=leverage, min_order=min_order, fee_rate=fee_rate, ts=ts,
                                z_score=z_score, coin_information=coin_information,
                                db_manager=postgre_manager, redis_manager=redis_orders)
                        else:
                            print('Short opened')
                        update_positions_flag = True
                        break

            # ----- Проверяем условия выхода из позиции -----
            first_leg = current_orders.filter(pl.col('token') == token_1)
            second_leg = current_orders.filter(pl.col('token') == token_2)

            if first_leg.is_empty() or second_leg.is_empty(): # Если данные не успели обновиться
                continue

            long_opened =  pairs.filter(
                    (pl.col('token_1') == token_1) & (pl.col('token_2') == token_2) & (pl.col('side') == 'long')
                ).height == 1
            short_opened =  pairs.filter(
                    (pl.col('token_1') == token_1) & (pl.col('token_2') == token_2) & (pl.col('side') == 'short')
                ).height == 1

            # --- Добавляем текущий z_score и profit в таблицу БД ---
            if long_opened or short_opened:
                t1_op = first_leg['price'][0]
                t2_op = second_leg['price'][0]
                q1 = first_leg['qty'][0]
                q2 = second_leg['qty'][0]

                side_1 = 'long' if long_opened else 'short'
                side_2 = 'short' if long_opened else 'long'

                curr_profit_1 = calculate_profit(open_price=t1_op, close_price=t1_med_price, n_coins=q1, side=side_1)
                curr_profit_2 = calculate_profit(open_price=t2_op, close_price=t2_med_price, n_coins=q2, side=side_2)
                curr_profit = curr_profit_1 + curr_profit_2
                zscore_arr.append((ts, 'bybit', token_1, token_2, curr_profit, z_score))

            # --- Выходим из позиции, если позволяют условия ---
            if zscore > high_out and long_opened:
                if not test_mode:
                    change_position(token_1, token_2, pos_side='close', t1_orig_side='long', t2_orig_side='short',
                        t1_data=t1_curr_data, t2_data=t2_curr_data, t1_usdt_amount=None, t2_usdt_amount=None,
                        leverage=leverage, min_order=min_order, fee_rate=fee_rate, ts=ts, z_score=z_score,
                        coin_information=coin_information, db_manager=postgre_manager, redis_manager=redis_orders)
                else:
                    print('Long closed')
                update_positions_flag = True
                break

            if zscore < low_out and short_opened:
                if not test_mode:
                    change_position(token_1, token_2, pos_side='close', t1_orig_side='short', t2_orig_side='long',
                        t1_data=t1_curr_data, t2_data=t2_curr_data, t1_usdt_amount=None, t2_usdt_amount=None,
                        leverage=leverage, min_order=min_order, fee_rate=fee_rate, ts=ts, z_score=z_score,
                        coin_information=coin_information, db_manager=postgre_manager, redis_manager=redis_orders)
                else:
                    print('Short closed')
                update_positions_flag = True
                break

        try:
            postgre_manager.add_data_to_zscore_history(zscore_arr)
        except Exception as err:
            print(zscore_arr)
            print(err)
            break
        sleep(0.9)

    except KeyboardInterrupt:
        print('\nЗавершение работы.')
        break

2025-09-13 02:15:00 Начинаем работу...
2025-09-13 02:15:01 Обновление плечей на бирже ByBit
2025-09-13 02:15:01 Старт основного цикла.
Текущее время: 2025-09-13 02:15:02
Завершение работы.

In [38]:
hour_1_df

shape: (5_040, 3)
┌─────────────────────────────┬──────────┬───────────┐
│ bucket                      ┆ token    ┆ avg_price │
│ ---                         ┆ ---      ┆ ---       │
│ datetime[μs, Europe/Moscow] ┆ str      ┆ f64       │
╞═════════════════════════════╪══════════╪═══════════╡
│ 2025-09-08 03:00:00 MSK     ┆ KSM_USDT ┆ 15.32     │
│ 2025-09-08 03:00:00 MSK     ┆ ZK_USDT  ┆ 0.05715   │
│ 2025-09-08 03:00:00 MSK     ┆ ZEN_USDT ┆ 7.270667  │
│ 2025-09-08 03:00:00 MSK     ┆ XRP_USDT ┆ 2.872083  │
│ 2025-09-08 03:00:00 MSK     ┆ XAI_USDT ┆ 0.046635  │
│ …                           ┆ …        ┆ …         │
│ 2025-09-13 02:00:00 MSK     ┆ XAI_USDT ┆ 0.056972  │
│ 2025-09-13 02:00:00 MSK     ┆ XRP_USDT ┆ 3.107517  │
│ 2025-09-13 02:00:00 MSK     ┆ ZEN_USDT ┆ 7.669667  │
│ 2025-09-13 02:00:00 MSK     ┆ ZK_USDT  ┆ 0.062523  │
│ 2025-09-13 02:00:00 MSK     ┆ ZRX_USDT ┆ 0.275483  │
└─────────────────────────────┴──────────┴───────────┘

In [27]:
t1, t2

(array([0.04203333, 0.04192667, 0.04190833, 0.04179167, 0.04174   ,
        0.04182833, 0.04190167, 0.04191833, 0.042065  , 0.042105  ,
        0.042105  , 0.04228167, 0.04235167, 0.04253833, 0.042505  ,
        0.042525  , 0.04248   , 0.04252   , 0.04283833, 0.04282333,
        0.04280167, 0.04266   , 0.04250833, 0.04245333, 0.04229833,
        0.04228667, 0.04236833, 0.04245167, 0.04236833, 0.04268167,
        0.04311167, 0.04337167, 0.04337833, 0.04327167, 0.043155  ,
        0.04335833, 0.043345  ]),
 array([0.017185  , 0.017155  , 0.01710833, 0.01709167, 0.01706833,
        0.017105  , 0.01718833, 0.01719833, 0.017305  , 0.01736833,
        0.01740833, 0.017495  , 0.01756833, 0.01770167, 0.01769833,
        0.017655  , 0.017585  , 0.01761167, 0.01780167, 0.01791167,
        0.01785167, 0.01774833, 0.01764167, 0.017575  , 0.01750167,
        0.01748167, 0.017575  , 0.01760167, 0.01756167, 0.01771833,
        0.01786167, 0.01799167, 0.01804167, 0.01799167, 0.01793167,
        0.01802833, 0.018005  ]))

In [30]:
t2_med_price

In [36]:
t1_curr_data

shape: (1, 8)
┌───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ symbol    ┆ ts         ┆ update_tim ┆ bidprice_0 ┆ bidvolume ┆ askprice_ ┆ askvolume ┆ avg_price │
│ ---       ┆ ---        ┆ e          ┆ ---        ┆ _0        ┆ 0         ┆ _0        ┆ ---       │
│ str       ┆ i64        ┆ ---        ┆ f64        ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│           ┆            ┆ datetime[μ ┆            ┆ f64       ┆ f64       ┆ f64       ┆           │
│           ┆            ┆ s]         ┆            ┆           ┆           ┆           ┆           │
╞═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FLOW_USDT ┆ 1757718904 ┆ 2025-09-13 ┆ 0.4225     ┆ 1578.3    ┆ 0.4226    ┆ 116.8     ┆ 0.42255   │
│           ┆            ┆ 02:15:04   ┆            ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [37]:
df_sec

shape: (183, 9)
┌──────────┬────────────┬───────────┬────────────┬───┬──────────┬───────────┬──────────┬───────────┐
│ exchange ┆ market_typ ┆ token     ┆ time       ┆ … ┆ bid_size ┆ ask_price ┆ ask_size ┆ avg_price │
│ ---      ┆ e          ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---       ┆ ---      ┆ ---       │
│ str      ┆ ---        ┆ str       ┆ datetime[μ ┆   ┆ f64      ┆ f64       ┆ f64      ┆ f64       │
│          ┆ str        ┆           ┆ s, Europe/ ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ Moscow]    ┆   ┆          ┆           ┆          ┆           │
╞══════════╪════════════╪═══════════╪════════════╪═══╪══════════╪═══════════╪══════════╪═══════════╡
│ bybit    ┆ linear     ┆ NEAR_USDT ┆ 2025-09-13 ┆ … ┆ 3798.6   ┆ 2.783     ┆ 4973.6   ┆ 2.7825    │
│          ┆            ┆           ┆ 02:15:04   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ IOTA_USDT ┆ 2025-09-13 ┆ … ┆ 3092.9   ┆ 0.1984    ┆ 15790.2  ┆ 0.19835   │
│          ┆            ┆           ┆ 02:15:04   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ SAND_USDT ┆ 2025-09-13 ┆ … ┆ 3065.0   ┆ 0.313     ┆ 27366.0  ┆ 0.31295   │
│          ┆            ┆           ┆ 02:15:04   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ FIL_USDT  ┆ 2025-09-13 ┆ … ┆ 3207.6   ┆ 2.559     ┆ 5206.2   ┆ 2.5585    │
│          ┆            ┆           ┆ 02:15:04   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ STRK_USDT ┆ 2025-09-13 ┆ … ┆ 9437.4   ┆ 0.1356    ┆ 54729.6  ┆ 0.13555   │
│          ┆            ┆           ┆ 02:15:04   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …        ┆ …         ┆ …        ┆ …         │
│ bybit    ┆ linear     ┆ BLUR_USDT ┆ 2025-09-13 ┆ … ┆ 21259.0  ┆ 0.08575   ┆ 865.0    ┆ 0.085745  │
│          ┆            ┆           ┆ 02:14:57   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ AKT_USDT  ┆ 2025-09-13 ┆ … ┆ 1925.3   ┆ 1.212     ┆ 360.5    ┆ 1.2115    │
│          ┆            ┆           ┆ 02:14:57   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ GMT_USDT  ┆ 2025-09-13 ┆ … ┆ 18525.0  ┆ 0.04495   ┆ 19901.0  ┆ 0.044945  │
│          ┆            ┆           ┆ 02:14:57   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ GTC_USDT  ┆ 2025-09-13 ┆ … ┆ 721.3    ┆ 0.3652    ┆ 752.6    ┆ 0.36515   │
│          ┆            ┆           ┆ 02:14:57   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
│ bybit    ┆ linear     ┆ APT_USDT  ┆ 2025-09-13 ┆ … ┆ 2023.27  ┆ 4.609     ┆ 2321.61  ┆ 4.6085    │
│          ┆            ┆           ┆ 02:14:57   ┆   ┆          ┆           ┆          ┆           │
│          ┆            ┆           ┆ MSK        ┆   ┆          ┆           ┆          ┆           │
└──────────┴────────────┴───────────┴────────────┴───┴──────────┴───────────┴──────────┴───────────┘

In [ ]:

             = current_data.filter(pl.col('symbol') == token_1)
            t2_curr_data = current_data.filter(pl.col('symbol') == token_2)

            # --- Проверка на актуальность текущих цен ---
            try:
                t1_ts = t1_curr_data['ts'].item()
                t2_ts = t2_curr_data['ts'].item()
            except ValueError: # Ситуация, когда после восстановления соединения не все токены успевают обновиться
                sleep(5)
                break

            if abs(t1_ts - t2_ts) > 10: # Если разница во времени между двумя ценами больше 10 секунд, пропускаем эту пару
                continue

            # Вместо текущей цены подставляем в функцию для расчёта z_score медианную цену за 5 секунд, чтобы избежать выбросов
            t1_df_sec = df_sec.filter(pl.col('token') == token_1)

In [ ]:
import json

In [ ]:
debug_arr.append({'token_1': token_1, 'token_2': token_2, 't1': t1, 't2': t2,
                  't1_med_price': t1_med_price, 't2_med_price': t2_med_price, 'zscore': zscore})

In [ ]:
st = '2025-09-09 10:47:12 [Long closed] Sell 267.1 OP for 0.775; Buy 288.9 SNX for 0.7075; z_score: 0.54'.split()

In [ ]:
token_1 = st[6]  + '_USDT'
token_2 = st[11] + '_USDT'
qty_1 = st[5]
qty_2 = st[10]
side = st[2][1:]
print(token_1, token_2, qty_1, qty_2, side)

# postgre_manager.add_pair_order(token_1=token_1, token_2=token_2, side=side, qty_1=qty_1, qty_2=qty_2)
# postgre_manager.delete_pair_order(token_1=token_1, token_2=token_2)

# redis_orders.add_order(exchange='bybit', token=token_1, qty=open_qty_1, side='short', 
#                        leverage=leverage, dp=dp_1, ord_id=str(uuid4()), ts=ts, price=short_price, status='created')
# redis_orders.add_order(exchange='bybit', token=token_2, qty=open_qty_2, price=long_price, side='long', 
#                        leverage=leverage, dp=dp_2, ord_id=str(uuid4()), ts=ts, status='created')

In [16]:
db_params = {'host': host, 'user': user, 'password': password, 'dbname': db_name}
postgre_manager = DBManager(db_params)
redis_orders = RedisManager(db_name = 'orders')
redis_orderbooks = RedisManager(db_name = 'orderbooks')

In [17]:
pairs = postgre_manager.get_table('pairs', df_type='polars')
pairs

shape: (5, 5)
┌───────────┬───────────┬───────┬───────────────┬───────────────┐
│ token_1   ┆ token_2   ┆ side  ┆ qty_1         ┆ qty_2         │
│ ---       ┆ ---       ┆ ---   ┆ ---           ┆ ---           │
│ str       ┆ str       ┆ str   ┆ decimal[*,8]  ┆ decimal[*,8]  │
╞═══════════╪═══════════╪═══════╪═══════════════╪═══════════════╡
│ CHZ_USDT  ┆ ENJ_USDT  ┆ short ┆ 4718.00000000 ┆ 2832.10000000 │
│ ARKM_USDT ┆ IOTA_USDT ┆ long  ┆ 307.00000000  ┆ 1020.80000000 │
│ AKT_USDT  ┆ FLOW_USDT ┆ long  ┆ 165.30000000  ┆ 474.80000000  │
│ STRK_USDT ┆ ZK_USDT   ┆ long  ┆ 1470.00000000 ┆ 3201.60000000 │
│ ROSE_USDT ┆ XAI_USDT  ┆ short ┆ 6719.00000000 ┆ 3504.00000000 │
└───────────┴───────────┴───────┴───────────────┴───────────────┘

In [18]:
current_orders = postgre_manager.get_table('current_orders', df_type='polars')
current_orders

shape: (10, 11)
┌───────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ token     ┆ exchange ┆ market_typ ┆ order_typ ┆ … ┆ usdt_amou ┆ realized_ ┆ leverage ┆ created_a │
│ ---       ┆ ---      ┆ e          ┆ e         ┆   ┆ nt        ┆ pnl       ┆ ---      ┆ t         │
│ str       ┆ str      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│           ┆          ┆ str        ┆ str       ┆   ┆ f64       ┆ f64       ┆          ┆ datetime[ │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ μs, Europ │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ e/Moscow] │
╞═══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ ARKM_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.814518 ┆ -0.109736 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 20:04:51  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ IOTA_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.05009 ┆ -0.109874 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆ 1         ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 20:04:51  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ FLOW_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.06275 ┆ -0.109888 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆ 2         ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 21:29:48  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ AKT_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.813417 ┆ -0.109734 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 21:29:49  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ ZK_USDT   ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.05473 ┆ -0.109879 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆ 8         ┆           ┆          ┆ 3         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 01:03:27  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ STRK_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.941438 ┆ -0.109875 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 3         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 01:03:28  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ XAI_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.918925 ┆ -0.10985  ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 3         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 01:04:11  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ ROSE_USDT ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.07638 ┆ -0.109903 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆ 4         ┆           ┆          ┆ 3         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 01:04:12  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ ENJ_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 99.98561  ┆ -0.109924 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 03:01:09  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
│ CHZ_USDT  ┆ bybit    ┆ linear     ┆ market    ┆ … ┆ 100.06849 ┆ -0.109894 ┆ 2.0      ┆ 2025-09-1 │
│           ┆          ┆            ┆           ┆   ┆ 1         ┆           ┆          ┆ 2         │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ 03:01:10  │
│           ┆          ┆            ┆           ┆   ┆           ┆           ┆          ┆ MSK       │
└───────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [19]:
pending_orders = redis_orders.get_pending_orders()
pending_orders

{}

In [20]:
trading_history = postgre_manager.get_table('trading_history')
trading_history

,token,exchange,market_type,order_type,order_side,open_price,close_price,open_usdt_amount,close_usdt_amount,qty,realized_pnl,leverage,created_at,closed_at,profit
id,,,,,,,,,,,,,,,
1,CELO_USDT,bybit,linear,market,buy,0.3075,0.3109,99.869398,100.9181,649.2,-0.220806,2.0,2025-09-10 14:53:27+03:00,2025-09-10 16:01:24+03:00,1.986474
2,IOTA_USDT,bybit,linear,market,sell,0.1926,0.1940,100.105041,100.6666,1037.8,-0.220667,2.0,2025-09-10 14:53:28+03:00,2025-09-10 16:01:25+03:00,-1.673587
3,SNX_USDT,bybit,linear,market,buy,0.6880,0.7074,99.883706,102.6437,290.2,-0.222720,2.0,2025-09-10 14:53:28+03:00,2025-09-10 16:49:38+03:00,5.407160
4,FLOW_USDT,bybit,linear,market,sell,0.4089,0.4166,100.059096,101.7754,488.6,-0.221837,2.0,2025-09-10 14:53:29+03:00,2025-09-10 16:49:39+03:00,-3.984057
5,ONDO_USDT,bybit,linear,market,buy,1.0248,1.0330,92.282728,92.9700,180.0,-0.203722,2.0,2025-09-10 16:01:25+03:00,2025-09-10 19:02:56+03:00,1.272278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,CELO_USDT,bybit,linear,market,buy,0.3099,0.3187,99.842683,102.6214,644.0,-0.222650,2.0,2025-09-12 15:36:42+03:00,2025-09-12 21:29:42+03:00,5.444550
67,ZEN_USDT,bybit,linear,market,sell,7.6480,7.6520,32.940663,32.9040,8.6,-0.072369,2.0,2025-09-12 20:34:37+03:00,2025-09-13 01:03:25+03:00,-0.106769
68,DOT_USDT,bybit,linear,market,buy,4.2480,4.2821,32.940107,33.1863,15.5,-0.072719,2.0,2025-09-12 20:34:38+03:00,2025-09-13 01:03:26+03:00,0.455831
69,ZRX_USDT,bybit,linear,market,buy,0.2733,0.2753,99.809365,100.4845,730.0,-0.220263,2.0,2025-09-12 17:07:51+03:00,2025-09-13 01:04:07+03:00,1.239737
70,SAND_USDT,bybit,linear,market,sell,0.3025,0.3116,99.989711,102.8280,660.0,-0.222918,2.0,2025-09-12 17:07:52+03:00,2025-09-13 01:04:08+03:00,-6.228918

In [21]:
trading_history['profit'].sum()

np.float64(26.85874248600004)

In [ ]:
# postgre_manager.delete_order('ONDO_USDT', 'bybit', 'linear')

In [ ]:
redis_orders.clear_orders_table()

In [ ]:
postgre_manager.clear_table('current_orders')

In [ ]:
postgre_manager.clear_table('pairs')

In [ ]:
# postgre_manager.clear_table('trading_history')

#### Open arbitrage orders

In [ ]:
logger.info('Запускаем основной цикл программы...')

arbitrage_tokens = {# 'ADA_USDT': {'long_exc': 'bybit', 'short_exc': 'okx', 'min_edge': 0.06},
                    # 'ALGO_USDT': {'long_exc': 'gate', 'short_exc': 'bybit', 'min_edge': -0.017}
                    'ADA_USDT': {'long_exc': 'gate', 'short_exc': 'bybit', 'min_edge': -10.017}
                   }

exit_flag = False
signal.signal(signal.SIGINT, signal_handler)
# ====================================
# Параметры запуска
limit_type = 'limit' # Первый ордер ставим по лучшей цене, а второй отправляем сразу же, как сматчился первый
n_ticks = Decimal('1')

demo = True
leverage = 2
max_usdt_order = 100
min_usdt_order = 10

max_orders = 3
# ====================================
# Основной цикл
while not exit_flag:
    token, data = None, None
    open_exc, cntr_side, cntr_qty = None, None, None
    long_exc, short_exc, min_edge = None, None, 512

    current_orders = postgre_manager.get_table('current_orders')
    n_current_orders = len(current_orders) // 2
    pending_orders = redis_order_manager.get_pending_orders()
    
    try:
        # Скачиваем текущие данные по ордербукам из Redis
        try:
            current_data = redis_price_manager.get_orderbooks(n_levels=5).filter(pl.col('symbol').is_in(arbitrage_tokens))
        except pl.exceptions.ColumnNotFoundError:
            sleep(1)
            continue

        # Проверка на то, что данные являются актуальными, что ни одна из бирж не подвисла
        if not is_data_up_to_date(current_data, time_thresh=10):
            logger.error(f'Устаревшие данные по ценам.')
            sleep(1)
        if len(current_data) == 0:
            raise Exception('No data!')
        
        for token, data in arbitrage_tokens.items():
            # Настройки направления сделок:
            long_exc = data['long_exc']
            short_exc = data['short_exc']
            min_edge = data['min_edge']

            # Определяем текущие цены
            df_long = current_data.filter((pl.col("exchange") == long_exc) & (pl.col("symbol") == token))
            df_short = current_data.filter((pl.col("exchange") == short_exc) & (pl.col("symbol") == token))
            long_price = df_long.select('askprice_0').item()
            short_price = df_short.select('bidprice_0').item()
            diff = (short_price / long_price - 1) * 100

            # Обработчик открытых в одном направлении лимитных ордеров.
            # ---------------------------------------------------------
            try:
                open_exc, cntr_side, cntr_qty = check_counter_conditions(token, pending_orders, long_exc, short_exc, long_price, short_price)
                cntr_qty = Decimal(cntr_qty)
                
                if open_exc == long_exc:
                    cntr_exc = short_exc
                elif open_exc == short_exc:
                    cntr_exc = long_exc
                
                cntr_ts = int(datetime.timestamp(datetime.now()))
                exc_name = cntr_exc + '_linear'

                resp = place_market_order(demo, exc_name, token, cntr_side, cntr_qty, coin_information)
                logger.info(f'[PLACE OPEN ORDER] {cntr_qty} {token}; {cntr_side} on {cntr_exc}')

                if cntr_exc == 'gate':
                    ord_id = resp['id']
                else:
                    ord_id = resp

                redis_order_manager.add_order(cntr_exc, token, float(cntr_qty), cntr_side, ord_id, cntr_ts, status='placed')
            
            except ValueError:
                pass                
            
            # Обработчик новых ордеров
            # -----------------------------------------------------------------------------            
            usdt_amount = check_open_conditions(token, current_orders, pending_orders, min_usdt_order, max_usdt_order)
            if usdt_amount:                
                long_exc_full = long_exc + '_linear'
                short_exc_full = short_exc + '_linear'
                
                ct = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                min_qty_step = get_step_info(coin_information, token, long_exc_full, short_exc_full)
                
                vol = leverage * float(usdt_amount) / max(long_price, short_price)
                volume = round_volume(volume=vol, qty_step=min_qty_step) 
                                
                usdt_amount = volume / Decimal(volume) * Decimal(max_usdt_order)

                # Сначала на обеих биржах меняем плечо, чтобы если есть проблемы со связью,
                #   всё отвалилось на этапе изменения плеча, а не после простановки ордера на первой бирже
                if token not in leverage_change_history:
                    set_leverage(demo=demo, exc=long_exc_full, symbol=token, leverage=leverage)
                    set_leverage(demo=demo, exc=short_exc_full, symbol=token, leverage=leverage)
                    logger.info(f'Leverage changing...')
    
                    leverage_change_history.append(token)
                    continue
                                                    
                
                if arbitrage_tokens[token]['long_exc'] == 'bybit':
                    first_order_exc = long_exc
                    side = 'buy'
                    price = long_price
                elif arbitrage_tokens[token]['short_exc'] == 'bybit':
                    first_order_exc = short_exc
                    side = 'sell'
                    price = short_price
                else:
                    first_order_exc = long_exc
                    side = 'buy'
                    price = long_price


                price_tick = get_price_scale(coin_information, token, first_order_exc + '_linear')
                if limit_type == 'instant':
                    l_price = Decimal(long_price) + n_ticks * price_tick
                    s_price = Decimal(short_price) - n_ticks * price_tick
                elif limit_type == 'limit':
                    l_price = Decimal(long_price) - n_ticks * price_tick
                    s_price = Decimal(short_price) + n_ticks * price_tick
                else:
                    raise NotImplementedError('Укажите корректный тип лимитного ордера!')

                l_price = l_price.normalize()
                s_price = s_price.normalize()

                price = l_price if first_order_exc == long_exc else s_price
                
                limit_diff = (s_price / l_price - 1) * 100

                
                logger.info(f'[PLACE OPEN ORDER] {volume} {token}; {side} on {first_order_exc}; {usdt_amount=:.2f}')
                logger.info(f'Current: long {long_price}, short {short_price}. Limit: long {l_price}, short {s_price}; diff: {diff:.3f}; limit diff: {limit_diff:.3f}; ')
        
                ts = int(datetime.timestamp(datetime.now()))
                
                resp = place_limit_order(demo=demo, 
                                exc=first_order_exc + '_linear', 
                                symbol=token, 
                                side=side, 
                                volume=volume, 
                                price=price,
                                coin_information=coin_information)
                
                if first_order_exc == 'gate':
                    ord_id = resp['id']
                else:
                    ord_id = resp
                
                redis_order_manager.add_order(exchange=first_order_exc, 
                                              token=token, 
                                              qty=float(volume), 
                                              side=side, 
                                              ord_id=ord_id, 
                                              ts=ts, 
                                              status='placed')
        
        sleep(0.05)

    except (KeyboardInterrupt, CancelledError):
        print('Завершение работы.')
        break

In [ ]:
handle_position(demo, exc='bybit_linear',
                symbol='ADA_USDT',
                order_type='limit',
                coin_information=coin_information)

In [ ]:
token

In [ ]:
pending_orders = redis_order_manager.get_pending_orders()
current_orders = postgre_manager.get_table('current_orders')
current_orders

In [ ]:
pending_orders

In [ ]:
redis_order_manager.add_order(exchange=first_order_exc, 
                                              token=token, 
                                              qty=float(volume), 
                                              side=side, 
                                              ord_id=ord_id, 
                                              ts=ts, 
                                              status='placed')

In [ ]:
redis_order_manager.delete_order(exchange='okx', token='ADA_USDT')

In [ ]:
redis_order_manager.clear_orders_table()

In [ ]:
# План
# 3. Добавить выскакивающее предупреждение, если по какому-то токену идёт большое отклонение на разных биржах, пригодное для арбитража.
# 4. Добавить автоматический стоп-лосс для шортовой сделки и take-profit для лонга
# 7. Можно попробовать реализовать выход из сделок по фандингу, ставя лимитный ордер на 1 - 1.5% от текущей цены - 
# при выплате фандинга цена резко просаживается, а где-то через минуту возвращается обратно. Можно попробовать это использовать.

# Надо посмотреть, считаются ли fees при учёте usdt_amount. Кажется, что у ByBit комиссия уже включена в usdt_amount,
# а у OKX - нет. _order_handler() и _position_handler() OKX usdt_amount считается как qty * price, так что fees не учитываются.

# To do:
# 3. Настроить нормальное логгирование. Продумать те статы, которые мне нужны на экране для анализа.
# 4. Настроить автоматическое обновление статов каждые 10 - 30 минут
# 5. Написать функцию для проверки открытых позиций на бирже и синхронизации с таблицей current_orders в БД.
# 6. Написать функцию, которая будет искать токены с максимальным отклонением от mean значения в текущий момент.

#### Manual open

In [ ]:
redis_order_manager = RedisManager(db_name = 'orders')

In [ ]:
demo = True
token = 'STRK_USDT'
side = 'buy'
usdt_amount = 20
leverage = 2
n_ticks = 2
stop_loss = 0.125

exc = 'bybit'
exc_full = f'{exc}_linear'

dp = coin_information[exc_full][token]['min_qty']

In [ ]:
current_data = redis_price_manager.get_orderbooks(n_levels=1).filter(pl.col('symbol') == token)
if len(current_data) == 0:
    raise Exception('No data!')

set_leverage(demo=demo, exc=exc_full, symbol=token, leverage=leverage)
logger.info(f'Leverage changing...')

In [ ]:
# Открываем лонг-ордер, тип заявки - лимитка на n_ticks лучше текущей цены.
current_data = redis_price_manager.get_orderbooks(n_levels=1).filter(pl.col('symbol') == token)
price = current_data.select(pl.when(side == 'buy').then(pl.col("askprice_0")).otherwise(pl.col("bidprice_0"))).item()
volume = round_size(leverage * usdt_amount / price, dp)

if not is_data_up_to_date(current_data, time_thresh=10):
    logger.error(f'Устаревшие данные по ценам.')
    raise Exception(f'Устаревшие данные по ценам.')
if len(current_data) == 0:
    logger.error(f'No data!')
    raise Exception(f'No data!')

dp = int(coin_information[exc_full][token]['price_scale'])
price_tick = get_price_scale(coin_information, token, exc_full)

# Выбираем цену для установки лимитного ордера на n_ticks тиков лучше текущей цены
if side == 'buy':
    curr_price = current_data.filter((pl.col('exchange') == exc)).select('askprice_0').item()
    price = curr_price - n_ticks * price_tick
    stop_loss = round(price / 2, dp)
elif side == 'sell':
    curr_price = current_data.filter((pl.col('exchange') == exc)).select('bidprice_0').item()
    price = curr_price + n_ticks * price_tick
    stop_loss = round(price * Decimal('1.8'), dp)

ord_id = place_market_order(demo=demo,
                            exc=exc_full,
                            symbol=token,
                            side=side,
                            volume=volume,
                            coin_information=coin_information,
                            stop_loss=stop_loss)
if ord_id:
    if exc == 'gate':
        ord_id = ord_id['id']
    ts = int(datetime.timestamp(datetime.now()))
    redis_order_manager.add_order(exchange=exc, 
                                  token=token, 
                                  qty=volume, 
                                  side=side,
                                  ord_id=ord_id,
                                  ts=ts,
                                  status='placed')

In [ ]:
if exc == 'gate':
    ord_id = ord_id['id']

cancel_id = cancel_order(demo=demo, exc=exc_full, symbol=token, order_id=ord_id)
if cancel_id:
    redis_order_manager.delete_order(exchange=exc, token=token)

In [ ]:
handle_position(demo=demo, exc=exc_full, symbol=token, order_type='market', coin_information=coin_information)

#### Вход в арбитражную сделку:

In [ ]:
def check_counter_conditions(token: str, 
                pending_orders: dict, 
                long_exc: str, 
                short_exc: str,
                long_price: float,
                short_price: float) -> bool:
    long_order_status = None
    short_order_status = None
    
    for exc, data in pending_orders.items():
        open_side = data.get(token, {}).get('side', None)
        status = data.get(token, {}).get('status', None)
        price_tick = get_price_scale(coin_information, token, exc + '_linear')
    
        if open_side == 'buy':
            if status == 'filled':
                long_order_status = 'filled'
                order_side = 'sell'
                price = Decimal(short_price) - n_ticks * price_tick
            elif status == 'placed':
                long_order_status = 'placed'
        elif open_side == 'sell':
            if status == 'filled':
                short_order_status = 'filled'
                order_side = 'buy'
                price = Decimal(long_price) + n_ticks * price_tick
            elif status == 'placed':
                short_order_status = 'placed'
    
    # Если ордер открыт только в одну сторону, тогда возвращаем размер и направление встречного ордера
    if (long_order_status == 'filled' and short_order_status is None
               ) or (
        long_order_status is None and short_order_status == 'filled'):

        qty = pending_orders[exc][token]['qty']

        return exc, order_side, qty
    
    return (False, False)

In [ ]:
"""
logger.info('Запускаем основной цикл программы...')
exc_list = ['bybit', 'okx', 'gate']
mt_list = ['linear', 'spot']

exit_flag = False
signal.signal(signal.SIGINT, signal_handler)
# ====================================
# Параметры запуска
max_mean = 1.2 # Максимальное значение mean в процентах, выше которого все крипто-пары отсекаются
min_std = 0.12 # Показатель std из stats_df для конкретной монеты
std_coef = 2.8 # На сколько умножаем std, вычисляя макс. расстояния от среднего значения
min_edge = 0.0
min_dist = 0.4

demo = False
leverage = 1
max_usdt_order = 20
min_usdt_order = 5

max_orders = 3

bybit_trade = BybitTrade(demo=demo)
okx_trade = OkxTrade(demo=demo)
gate_client = GateTrade(demo=demo)
trading_clients = {'bybit': bybit_trade, 'okx': okx_trade, 'gate': gate_client}

# ====================================
# Основной цикл
while not exit_flag:
    token, data = None, None
    df_in = pd.DataFrame()
    token_dict = dict()
    syms = []

    current_orders = postgre_manager.get_table('current_orders')
    n_current_orders = len(current_orders) // 2
    
    try:
        # Скачиваем текущие данные по ордербукам из Redis
        try:
            current_data = redis_manager.get_orderbooks(n_levels=5)
        except pl.exceptions.ColumnNotFoundError:
            sleep(1)
            continue

        # Проверка на то, что данные являются актуальными, что ни одна из бирж не подвисла
        sorted_df = current_data.sort(by='ts')
        oldest_ts_exc = sorted_df.select("exchange").head(1).item()
        last_entry = sorted_df.filter(pl.col('exchange') == oldest_ts_exc).select("ts").tail(1).item()
        time_delta = int(datetime.timestamp(datetime.now())) - last_entry
        
        # Если данные на бирже последний раз обновлялись больше 20 секунд назад, прерываем работу программы
        if time_delta > 10:
            logger.error(f'Отсутствует соединение с биржей {oldest_ts_exc}.')
            sleep(5)
            continue

        # Здесь будет обработчик текущих лимитных ордеров.
        # Args: order_price, order_side, order_time
        # Если цена, полученная через Redis, доходит до цены ордера - отправляем запрос на подтверждение ордера.
        # Если всё норм и ордер сматчился - отправляем лимитку в обратную сторону.
        # Если прошло 10-15-20 секунд и ордер не выкупили (а цена уехала), отменяем ордер
        # После всех манипуляций возвращаем переменные и order_status в исходное состояние.
        
        # Продолжаем, если данные обновляются регулярно
        stats_data = postgre_manager.get_table('stats_data')
        stats_data = pl.from_pandas(stats_data)
        df_in = find_tokens_to_open_order(current_data=current_data, 
                                          stats_data=stats_data, 
                                          max_mean=max_mean, 
                                          min_std=min_std, 
                                          std_coef=std_coef, 
                                          min_edge=min_edge,
                                          min_dist=min_dist)
        
        # Создадим словарь с токенами для того, чтобы посчитать, сколько usdt ещё доступно для открытия ордера.
        if not df_in.is_empty():
            # Если в df_in есть несколько вариантов для одного токена:
            n_counts = df_in["token"].value_counts(sort=True).select('count').head(1).item()
            if n_counts > 1:
                print('Есть несколько вариантов для одного токена')
                df_in_copy = df_in.clone()
                if bybit_diff - 0.1 < other_diff:
                    df_in = df_in.filter((pl.col("token") != token) | ((pl.col("long_exc") != "bybit") & (pl.col("short_exc") != "bybit")))
                else:
                    df_in = df_in.filter((pl.col("token") != token) | ((pl.col("long_exc") == "bybit") | (pl.col("short_exc") == "bybit")))
                
                exit_flag = True
                break
            
            token_list = df_in['token'].to_list()
                        
            for token in token_list:
                if token in current_orders['token'].to_list():
                    token_dict[token] = max_usdt_order - current_orders[current_orders['token'] == token].iloc[0]['usdt_amount']
                else:
                    token_dict[token] = max_usdt_order
        else:
            token_list = []

        for row in df_in.to_dicts():            
            token = row["token"]
            long_exc = row["long_exc"]
            short_exc = row["short_exc"]
                        
            if token_dict[token] < min_usdt_order:
                continue
            
            usdt_remain = 0 # Сбрасываем настройки для безопасности
            
            min_edge = row["thresh"]
            price_long = row['ask_long']
            price_short = row['bid_short']
            thresh = row['thresh']
        
            df_long = current_data.filter((pl.col("exchange") == long_exc) & (pl.col("symbol") == token))
            df_short = current_data.filter((pl.col("exchange") == short_exc) & (pl.col("symbol") == token))
            ask_price = df_long.select('askprice_0', 'askprice_1', 'askprice_2', 'askprice_3', 'askprice_4').row(0)
            ask_size = df_long.select('askvolume_0', 'askvolume_1', 'askvolume_2', 'askvolume_3', 'askvolume_4').row(0)
            bid_price = df_short.select('bidprice_0', 'bidprice_1', 'bidprice_2', 'bidprice_3', 'bidprice_4').row(0)
            bid_size = df_short.select('bidvolume_0', 'bidvolume_1', 'bidvolume_2', 'bidvolume_3', 'bidvolume_4').row(0)
            long_ob = [[price, size] for price, size in zip(ask_price, ask_size)]
            short_ob = [[price, size] for price, size in zip(bid_price, bid_size)]
            
            usdt_remain = token_dict[token]
            edge = max(thresh, min_edge)
            
            res = get_open_volume(long_orderbook=long_ob, 
                                  short_orderbook=short_ob, 
                                  min_edge=edge, 
                                  max_usdt=usdt_remain, # Умножаем на 2, чтобы был запас по ликвидности
                                  debug=False)
            
            # Если в ордербуке достаточно ликвидности для открытия ордера с заданным diff, открываем сделку
            # Проверяем, что у нас есть свободные слоты на открытие ордеров, или что ордер уже открыт и мы можем докупиться
            if res['usdt_amount'] >= min_usdt_order and (n_current_orders < max_orders or token in current_orders['token'].to_list()):
                # Если мне предлагают открыть ордер в направлении, отличном от уже существующего на бирже
                if token in current_orders['token'].to_list():
                    try:
                        long_position_side = current_orders[(current_orders['token'] == token) & 
                                                            (current_orders['exchange'] == long_exc)]['order_side'].item()
                        short_position_side = current_orders[(current_orders['token'] == token) & 
                                                            (current_orders['exchange'] == short_exc)]['order_side'].item()
    
                        if long_position_side == 'sell' or short_position_side == 'buy':
                            continue
                    except ValueError:
                        # Это означает, что мне предлагают открыть ещё одну сделку на другой бирже
                        continue
                
                
                long_exc_full = long_exc + '_linear'
                short_exc_full = short_exc + '_linear'
                
                ct = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                min_qty_step = get_step_info(coin_information, token, long_exc_full, short_exc_full)
                curr_diff = res['edge']
                volume = round_volume(volume=res['volume'], qty_step=min_qty_step) # Делим на 2, избавляясь от коэффа
                
                # Если при округлении цена упала меньше минимально возможной
                if volume < min_qty_step:
                    continue
                
                usdt_amount = volume / Decimal(res['volume']) * Decimal(res['usdt_amount'])
                mean = row['mean']
                std = row['std']
                deviation = (curr_diff - mean) / std

                long_price = long_ob[0][0]
                short_price = short_ob[0][0]
                
                # Сначала на обеих биржах меняем плечо, чтобы если есть проблемы со связью,
                #   всё отвалилось на этапе изменения плеча, а не после простановки ордера на первой бирже
                if token not in leverage_change_history:
                    set_leverage(demo=demo, exc=long_exc_full, symbol=token, leverage=leverage)
                    set_leverage(demo=demo, exc=short_exc_full, symbol=token, leverage=leverage)
                    logger.info(f'Leverage changing...')

                    leverage_change_history.append(token)
                    continue
                
                # Для дебага добавляем ордербук, на основании которого был открыт ордер, в список, хранящий историю
                orders_history.append({'time': ct, 'row': row, 'res': res, 'qty_step': min_qty_step})
                with open("./data/open_order_history.pkl", "wb") as f:
                    pickle.dump(orders_history, f)

                logger.info(f'[PLACE OPEN ORDER] {volume} {token}; diff: {curr_diff:.3f}, {thresh=:.3f}, {mean=:.3f}, {std=:.3f}; {deviation=:.3f}')
                logger.info(f'Цены во время простановки ордера. long: {price_long} ({long_exc}), short: {price_short} ({short_exc}); {usdt_amount=:.2f}')
                                    
                # Открываем лонг-ордер
                long_order_resp = place_market_order(demo=demo, exc=long_exc_full, symbol=token, side='buy', volume=volume)
                logger.info(f'Лонг ордер ({long_exc}) отправлен на биржу.')
                
                # Открываем шорт-ордер
                short_order_resp = place_market_order(demo=demo, exc=short_exc_full, symbol=token, side='sell', volume=volume)
                logger.info(f'Шорт ордер ({short_exc}) отправлен на биржу.')
                

                # Обрабатываем полученные ответы и заносим ордеры в БД
                handle_position(demo=demo, exc=long_exc_full, symbol=token, order_type='market')
                handle_position(demo=demo, exc=short_exc_full, symbol=token, order_type='market')
        
        sleep(0.02)
    except (KeyboardInterrupt, CancelledError):
        print('Завершение работы.')
        break
    # except RuntimeError as e:
    #     print(f"Ошибка выполнения: {e}")


"""