In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

import polars as pl
import pandas as pd
import numpy as np

In [8]:
bb_df = pd.read_csv('./data/bybit.csv')
gate_df = pd.read_csv('./data/gate.csv')

In [9]:
bb_df

,Contracts,Trade Type,Qty,Entry Price,Realized P&L,Filled Price,Exit Type,Filled/Settlement Time(UTC+0),Create Time
0,AVLUSDT,SELL,20.00,0.39680,-0.607657,0.36720,Trade,09:35 2025-03-06,09:35 2025-03-06
1,AVLUSDT,SELL,50.00,0.39680,-1.513149,0.36732,Trade,09:30 2025-03-06,09:30 2025-03-06
2,AIOZUSDT,BUY,30.00,0.34930,0.044581,0.34660,Trade,09:22 2025-03-06,09:22 2025-03-06
3,AIOZUSDT,BUY,40.00,0.34930,0.043425,0.34700,Trade,09:22 2025-03-06,09:22 2025-03-06
4,AIOZUSDT,BUY,10.00,0.34930,0.010856,0.34700,Trade,09:20 2025-03-06,09:20 2025-03-06
5,XCHUSDT,SELL,1.78,16.79000,-0.433199,16.58000,Trade,07:21 2025-03-06,07:21 2025-03-06
6,AIOZUSDT,BUY,50.00,0.34944,0.098282,0.34700,Trade,04:04 2025-03-06,04:04 2025-03-06
7,REQUSDT,BUY,156.00,0.11744,0.012537,0.11720,Trade,04:03 2025-03-06,04:00 2025-03-06
8,KAITOUSDT,BUY,17.00,1.76810,-1.318808,1.82790,Trade,03:10 2025-03-06,03:10 2025-03-06

In [7]:
df['Realized P&L'].sum()

-3.6631299999999998

In [10]:
gate_df

,Contract,Order ID,Deal amount,Deal price,Role,Time
0,AVL/USDT,216172782147156290,2,0.36710,taker,2025-03-06 12:35:43
1,AVL/USDT,216172782147154992,5,0.36610,taker,2025-03-06 12:30:46
2,AIOZ/USDT,7881299356359684,-3,0.34280,taker,2025-03-06 12:22:56
3,AIOZ/USDT,7881299356359619,-4,0.34290,taker,2025-03-06 12:22:35
4,AIOZ/USDT,7881299356359424,-1,0.34280,taker,2025-03-06 12:20:40
5,XCH/USDT,200128708454973328,10,16.57000,taker,2025-03-06 10:21:04
6,XCH/USDT,200128708454973328,1770,16.57400,taker,2025-03-06 10:21:04
7,XCH/USDT,200128708454959167,-1127,16.78400,taker,2025-03-06 08:28:24
8,XCH/USDT,200128708454959167,-653,16.79800,taker,2025-03-06 08:28:24
9,AIOZ/USDT,7881299356326879,3,0.34730,taker,2025-03-06 07:58:54
10,AIOZ/USDT,7881299356326879,5,0.34830,taker,2025-03-06 07:58:54
11,AVL/USDT,216172782147065056,-7,0.39650,taker,2025-03-06 07:22:01
12,AIOZ/USDT,7881299356323273,-5,0.34140,taker,2025-03-06 07:04:43
13,REQ/USDT,154811237194314905,-156,0.11628,taker,2025-03-06 07:03:34
14,KAITO/USDT,218424582105120917,-17,1.83640,maker,2025-03-06 06:21:16
15,KAITO/USDT,218424582105115139,6,1.83210,maker,2025-03-06 06:17:22
16,KAITO/USDT,218424582105115139,4,1.83210,maker,2025-03-06 06:17:21
17,KAITO/USDT,218424582105115139,7,1.83210,maker,2025-03-06 06:17:21
18,KAITO/USDT,218424582105094541,-17,1.82750,taker,2025-03-06 06:10:44
19,AIOZ/USDT,7881299356312614,2,0.34770,taker,2025-03-06 05:15:37
20,AIOZ/USDT,7881299356311178,3,0.34520,taker,2025-03-06 05:02:55
21,BONE/USDT,34058472188678297,1,0.25950,taker,2025-03-06 04:50:20
22,BONE/USDT,34058472188678126,-1,0.25790,taker,2025-03-06 04:48:57
23,REQ/USDT,154811237194311357,156,0.11710,taker,2025-03-06 04:01:42
24,KAITO/USDT,218424582104132869,17,1.75380,taker,2025-03-06 03:25:54