#### SQL запросы для создания и редактирования таблиц в БД

In [ ]:
# CREATE TABLE current_orders (
#     token TEXT NOT NULL,
#     exchange TEXT NOT NULL,
#     market_type TEXT NOT NULL,
#     order_type TEXT NOT NULL,
#     order_id TEXT NOT NULL,
#     order_side TEXT NOT NULL,
#     price NUMERIC(18,8) NOT NULL,
#     avg_price NUMERIC(18,8),
#     usdt_amount NUMERIC(18,10),
#     qty NUMERIC(18,8) NOT NULL,
#     fee NUMERIC(18,8) NOT NULL,
#     created_at TIMESTAMPTZ DEFAULT now(),
#     PRIMARY KEY (token, exchange, market_type)
# );

# CREATE TABLE trading_history (
#     id SERIAL PRIMARY KEY,
#     token TEXT NOT NULL,
#     exchange TEXT NOT NULL,
#     market_type TEXT NOT NULL,
#     order_type TEXT NOT NULL,
#     order_side TEXT NOT NULL,
#     open_price NUMERIC(18,8) NOT NULL,
#     close_price NUMERIC(18,8) NOT NULL,
#     open_avg_price NUMERIC(18,8),
#     close_avg_price NUMERIC(18,8),
#     open_usdt_amount NUMERIC(18,10),
#     close_usdt_amount NUMERIC(18,10),
#     qty NUMERIC(18,8) NOT NULL,
#     open_fee NUMERIC(18,8) NOT NULL,
#     close_fee NUMERIC(18,8) NOT NULL,
#     created_at TIMESTAMPTZ,
#     closed_at TIMESTAMPTZ DEFAULT now(),
#     profit NUMERIC(18,8)
# );

#### Код

In [1]:
from jaref_bot.db.db_manager import DBManager
import pandas as pd
from config import host, user, password, db_name
from psycopg2.errors import UniqueViolation

db_params = {'host': host, 'user': user, 'password': password, 'database': db_name}
db_manager = DBManager(db_params)

db_manager.get_auto_copy_trigger_state()

'DISABLED'

In [2]:
# db_manager.set_auto_copy_trigger_state('disable')

In [ ]:
# db_manager.get_token_history('COMP_USDT').tail(10)

In [ ]:
# try:
#     db_manager.add_order(token='ETH_USDT', exchange='bybit', market_type='linear', order_type='market', order_id=12345,
#                                     order_side='buy', price=3500, avg_price=3650, usdt_amount=43800, qty=12, fee=10)
# except UniqueViolation:
#     db_manager.close_order(token="ETH_USDT", exchange='bybit', market_type='linear', close_price=3510, close_avg_price=3660,
#                        close_usdt_amount=43920, qty=12, close_fee=10)

In [29]:
db_manager.order_exists("ETH_USDT")

False

In [ ]:
db_manager.get_order("ADAUSDT")

In [ ]:
# db_manager.close_order(token="ETH_USDT", exchange='bybit', market_type='linear', close_price=3510, close_avg_price=3660,
#                        qty=12, close_fee=10)

In [ ]:
# db_manager.add_order(token="ETH_USDT", exchange="OKX", price=104500, avg_price=104520, qty=2, fee=1, exc_id='123124')

In [21]:
db_manager.clear_table('trading_history')
db_manager.clear_table('current_orders')

In [34]:
db_manager.get_table('current_orders')

,token,exchange,market_type,order_type,order_id,order_side,price,avg_price,usdt_amount,qty,fee,created_at
0,STPT,gate,linear,market,order_id,buy,0.0759842857,0.0759842857,21.2756000000,280.0000000000,0.0005000000,2025-02-08 10:04:48+03:00
1,STPT,bybit,linear,market,order_id,sell,0.0762000000,0.0762000000,21.3360000000,280.0000000000,0.0010000000,2025-02-08 10:04:48+03:00

In [35]:
db_manager.get_table('trading_history')

Empty DataFrame
Columns: [token, exchange, market_type, order_type, order_side, open_price, close_price, open_avg_price, close_avg_price, open_usdt_amount, close_usdt_amount, qty, open_fee, close_fee, created_at, closed_at, profit]
Index: []

In [24]:
db_manager.get_table('trading_history')['profit'].sum()

0

In [37]:
(0.0762 / 0.0759 - 1) * 100

0.39525691699606735

In [28]:
# db_manager.clear_table('current_data')

In [32]:
current_data = db_manager.get_table('current_data')

In [33]:
current_data[current_data['token'] == 'FLR_USDT']

     exchange market_type     token           timestamp bid_price ask_price
48      bybit      linear  FLR_USDT 2025-02-08 09:52:03   0.02181   0.02182
213     bybit        spot  FLR_USDT 2025-02-08 09:52:03   0.02186   0.02188
532      gate      linear  FLR_USDT 2025-02-08 09:52:03   0.02174    0.0218
797      gate        spot  FLR_USDT 2025-02-08 09:52:03  0.021893  0.021903
1113      okx        spot  FLR_USDT 2025-02-08 09:52:03   0.02187   0.02189

In [ ]:
best_params_df = pd.read_parquet('./data/best_params.parquet')
best_params_df['token'] = best_params_df['token'].astype(str) + '_USDT'

spot_params = best_params_df[best_params_df['market_type'] == 'spot']
linear_params = best_params_df[best_params_df['market_type'] == 'linear']

In [ ]:
# Обновляем данные
current_data = db_manager.get_table('current_data')


# Находим токены для выхода из сделки
df_out = tdf[tdf['market_type'] == 'spot'][['token', 'max']].reset_index(drop=True)
df_out = df_out.merge(tdf[tdf['market_type'] == 'linear'][['token', 'min']], on='token')
df_out['diff_perc'] = (df_out['max'] / df_out['min'] - 1) * 100

df_out = df_out.merge(spot_params[['token', 'in', 'out', 'mean', 'profit']], on='token')
df_out = df_out[df_out['diff_perc'] > df_out['out']]

In [21]:
from decimal import Decimal

In [38]:
Decimal('12.32').to_eng_string()

'12.32'