In [1]:
%load_ext autoreload
%autoreload 2

from jaref_bot.data.http_api import ExchangeManager, BybitRestAPI, OKXRestAPI, GateIORestAPI
import polars as pl
from datetime import datetime
from tqdm.notebook import tqdm
import requests

from jaref_bot.strategies.funding import get_arbitrage_fund
from jaref_bot.db.postgres_manager import DBManager
from jaref_bot.config.credentials import host, user, password, db_name

db_params = {'host': host, 'user': user, 'password': password, 'dbname': db_name}
db_manager = DBManager(db_params)

In [2]:
df = db_manager.get_table('funding_data')
df = pl.from_pandas(df)

In [3]:
get_arbitrage_fund(df, 0.2)

shape: (6, 11)
┌─────────────┬───────────┬─────────┬─────────┬───┬──────────────┬──────────────┬─────────────────────┬──────────┐
│ token       ┆ fr_bybit  ┆ fr_gate ┆ fr_okx  ┆ … ┆ nft_bybit    ┆ nft_gate     ┆ nft_okx             ┆ max_diff │
│ ---         ┆ ---       ┆ ---     ┆ ---     ┆   ┆ ---          ┆ ---          ┆ ---                 ┆ ---      │
│ str         ┆ f64       ┆ f64     ┆ f64     ┆   ┆ datetime[ns] ┆ datetime[ns] ┆ datetime[ns]        ┆ f64      │
╞═════════════╪═══════════╪═════════╪═════════╪═══╪══════════════╪══════════════╪═════════════════════╪══════════╡
│ FORTH_USDT  ┆ -1.894092 ┆ -1.5    ┆ null    ┆ … ┆ 2025-04-09   ┆ 2025-04-09   ┆ null                ┆ 0.394092 │
│             ┆           ┆         ┆         ┆   ┆ 03:00:00     ┆ 03:00:00     ┆                     ┆          │
│ BAL_USDT    ┆ -0.367452 ┆ -0.3088 ┆ -0.5878 ┆ … ┆ 2025-04-09   ┆ 2025-04-09   ┆ 2025-04-09 03:00:00 ┆ 0.279    │
│             ┆           ┆         ┆         ┆   ┆ 03:00:00     ┆ 03:00:00     ┆                     ┆          │
│ MBL_USDT    ┆ -0.243841 ┆ 0.01    ┆ null    ┆ … ┆ 2025-04-09   ┆ 2025-04-09   ┆ null                ┆ 0.253841 │
│             ┆           ┆         ┆         ┆   ┆ 03:00:00     ┆ 03:00:00     ┆                     ┆          │
│ OMG_USDT    ┆ -0.221314 ┆ 0.01    ┆ null    ┆ … ┆ 2025-04-09   ┆ 2025-04-09   ┆ null                ┆ 0.231314 │
│             ┆           ┆         ┆         ┆   ┆ 03:00:00     ┆ 03:00:00     ┆                     ┆          │
│ AGI_USDT    ┆ -0.203089 ┆ 0.005   ┆ null    ┆ … ┆ 2025-04-09   ┆ 2025-04-08   ┆ null                ┆ 0.208089 │
│             ┆           ┆         ┆         ┆   ┆ 03:00:00     ┆ 23:00:00     ┆                     ┆          │
│ BADGER_USDT ┆ -0.041059 ┆ -0.2443 ┆ -0.2278 ┆ … ┆ 2025-04-08   ┆ 2025-04-09   ┆ 2025-04-09 03:00:00 ┆ 0.203241 │
│             ┆           ┆         ┆         ┆   ┆ 23:00:00     ┆ 03:00:00     ┆                     ┆          │
└─────────────┴───────────┴─────────┴─────────┴───┴──────────────┴──────────────┴─────────────────────┴──────────┘

In [4]:
df.filter(pl.col('funding_rate') > 0.1).sort(by='funding_rate', descending=True)

shape: (1, 7)
┌───────────┬──────────┬───────────┬───────────┬──────────────┬───────────────┬─────────────────────┐
│ token     ┆ exchange ┆ ask_price ┆ bid_price ┆ funding_rate ┆ fund_interval ┆ next_fund_time      │
│ ---       ┆ ---      ┆ ---       ┆ ---       ┆ ---          ┆ ---           ┆ ---                 │
│ str       ┆ str      ┆ f64       ┆ f64       ┆ f64          ┆ i64           ┆ datetime[ns]        │
╞═══════════╪══════════╪═══════════╪═══════════╪══════════════╪═══════════════╪═════════════════════╡
│ DUCK_USDT ┆ okx      ┆ 0.0       ┆ 0.0       ┆ 0.1311       ┆ 4             ┆ 2025-04-08 23:00:00 │
└───────────┴──────────┴───────────┴───────────┴──────────────┴───────────────┴─────────────────────┘

In [5]:
df.filter(pl.col('funding_rate') < -0.5).sort(by='funding_rate')

shape: (7, 7)
┌────────────────┬──────────┬───────────┬───────────┬──────────────┬───────────────┬─────────────────────┐
│ token          ┆ exchange ┆ ask_price ┆ bid_price ┆ funding_rate ┆ fund_interval ┆ next_fund_time      │
│ ---            ┆ ---      ┆ ---       ┆ ---       ┆ ---          ┆ ---           ┆ ---                 │
│ str            ┆ str      ┆ f64       ┆ f64       ┆ f64          ┆ i64           ┆ datetime[ns]        │
╞════════════════╪══════════╪═══════════╪═══════════╪══════════════╪═══════════════╪═════════════════════╡
│ FORTH_USDT     ┆ bybit    ┆ 2.8197    ┆ 2.8194    ┆ -1.894092    ┆ 8             ┆ 2025-04-09 03:00:00 │
│ FORTH_USDT     ┆ gate     ┆ 2.798     ┆ 2.792     ┆ -1.5         ┆ 8             ┆ 2025-04-09 03:00:00 │
│ NULS_USDT      ┆ bybit    ┆ 0.0481    ┆ 0.0479    ┆ -1.160565    ┆ 4             ┆ 2025-04-08 23:00:00 │
│ NULS_USDT      ┆ gate     ┆ 0.04792   ┆ 0.04784   ┆ -1.1303      ┆ 4             ┆ 2025-04-08 23:00:00 │
│ JAILSTOOL_USDT ┆ bybit    ┆ 0.00723   ┆ 0.007221  ┆ -0.596393    ┆ 4             ┆ 2025-04-08 23:00:00 │
│ BAL_USDT       ┆ okx      ┆ 0.0       ┆ 0.0       ┆ -0.5878      ┆ 8             ┆ 2025-04-09 03:00:00 │
│ CARV_USDT      ┆ bybit    ┆ 0.2979    ┆ 0.2977    ┆ -0.579222    ┆ 4             ┆ 2025-04-08 23:00:00 │
└────────────────┴──────────┴───────────┴───────────┴──────────────┴───────────────┴─────────────────────┘

In [6]:
df.filter((pl.col('fund_interval').is_in([1, 2])) & (pl.col('fund_interval') < -0.2)).sort(by='funding_rate')

shape: (0, 7)
┌───────┬──────────┬───────────┬───────────┬──────────────┬───────────────┬────────────────┐
│ token ┆ exchange ┆ ask_price ┆ bid_price ┆ funding_rate ┆ fund_interval ┆ next_fund_time │
│ ---   ┆ ---      ┆ ---       ┆ ---       ┆ ---          ┆ ---           ┆ ---            │
│ str   ┆ str      ┆ f64       ┆ f64       ┆ f64          ┆ i64           ┆ datetime[ns]   │
╞═══════╪══════════╪═══════════╪═══════════╪══════════════╪═══════════════╪════════════════╡
└───────┴──────────┴───────────┴───────────┴──────────────┴───────────────┴────────────────┘

#### Ситуация по конкретной монете

In [ ]:
from jaref_bot.data.http_api import ExchangeManager, BybitRestAPI, GateIORestAPI

import matplotlib.pyplot as plt

import pandas as pd
import polars as pl
import numpy as np
from datetime import datetime

exc_manager = ExchangeManager()
exc_manager.add_market("bybit_linear", BybitRestAPI('linear'))
exc_manager.add_market("okx_linear", OKXRestAPI('linear'))
exc_manager.add_market("gate_linear", GateIORestAPI('linear'))

In [ ]:
interval = '1m'
n_iters = 1
sym = 'BIGTIME_USDT'

bb_df, okx_df, gate_df = await exc_manager.get_candles(symbol=sym, interval=interval, n_iters=n_iters)
assert bb_df['Exchange'].iloc[0] == 'bybit'
assert okx_df['Exchange'].iloc[0] == 'okx'
assert gate_df['Exchange'].iloc[0] == 'gate'

In [ ]:
exc_long = 'bybit'
exc_short = 'gate'

long_df = bb_df.copy()
short_df = gate_df.copy()

In [ ]:
df = long_df[['Close']].merge(short_df[['Close']], how='inner', on='Date', suffixes=(f'_long', f'_short'))
df['perc_diff'] = (df[f'Close_short'] / df[f'Close_long'] - 1) * 100
df['perc_diff'].iloc[:].plot(figsize=(14, 2));

In [ ]:
edge_time = '2025-04-03 06:40'
orig_df = df[df.index < edge_time]
curr_df = df[df.index > edge_time]

minv, maxv, meanv, stdv = orig_df['perc_diff'].agg(['min', 'max', 'mean', 'std'])
cminv, cmaxv, cmeanv, cstdv = curr_df['perc_diff'].agg(['min', 'max', 'mean', 'std'])

curr_diff = curr_df['perc_diff'].iloc[-1]
# curr_dev = (curr_diff - meanv) / stdv

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(18, 3), gridspec_kw={'width_ratios': [1, 1]})
ax1.set_title(f'Usual diff. mean: {meanv:.3f}, std: {stdv:.1f}')
ax1.plot(orig_df.index, orig_df['perc_diff'])
ax1.axhline(y=meanv, color='black', linestyle='-') # mean
ax1.axhline(y=meanv + 2 * stdv, color='b', linestyle='-'); # high bound
ax1.axhline(y=meanv - 2 * stdv, color='b', linestyle='-'); # low bound

ax2.set_title(f'Current diff. mean: {cmeanv:.3f}, std: {cstdv:.1f}, {curr_diff=:.3f}')
ax2.plot(curr_df.index, curr_df['perc_diff']);
ax2.axhline(y=cmeanv, color='black', linestyle='-') # mean
ax2.axhline(y=cmeanv + 2 * cstdv, color='b', linestyle='-'); # high bound
ax2.axhline(y=cmeanv - 2 * cstdv, color='b', linestyle='-'); # low bound

plt.tight_layout()
plt.show()

In [ ]:
def calculate_profit(qty: float, 
                     lm_open_price: float, 
                     lm_open_fee_perc: float, 
                     sm_open_price: float, 
                     sm_open_fee_perc: float,
                     lm_close_price: float,
                     lm_close_fee_perc: float, 
                     sm_close_price: float,
                     sm_close_fee_perc: float,
                    ):
    """
    Рассчитывает прибыль арбитражной сделки на основании цен открытия и закрытия, размера комиссии и фандинга.
    Diff всегда указывается как разница в процентах между курсом продажи и курсом покупки: 
        diff = (bid_price / ask_price - 1) * 100
    Args:
        qty - Количество купленных монет.
        lm_open_price - Ask price на лонг-рынке при открытии сделки.
        lm_open_fee_perc - Размер комиссии, указанный в процентах, при открытии сделки на лонг-рынке.
        sm_open_price - Bid price на шорт-рынке при открытии сделки.
        sm_open_fee_perc - Размер комиссии, указанный в процентах, при открытии сделки на шорт-рынке.
        lm_close_price - Bid price на лонг-рынке при закрытии сделки.
        lm_close_fee_perc - Размер комиссии, указанный в процентах, при закрытии сделки на лонг-рынке.
        sm_close_price - Ask price на шорт-рынке при закрытии сделки.
        sm_close_fee_perc - Размер комиссии, указанный в процентах, при закрытии сделки на шорт-рынке.

        
    """

    long_open_fee_perc = lm_open_fee_perc / 100
    short_open_fee_perc = sm_open_fee_perc / 100
    long_close_fee_perc = lm_close_fee_perc / 100
    short_close_fee_perc = sm_close_fee_perc / 100
    
    long_open_fee = qty * lm_open_price * long_open_fee_perc
    short_open_fee = qty * sm_open_price * short_open_fee_perc
    long_close_fee = qty * lm_close_price * long_close_fee_perc
    short_close_fee = qty * sm_close_price * short_close_fee_perc

    
    open_diff = (sm_open_price / lm_open_price - 1) * 100
    close_diff = (lm_close_price / sm_close_price - 1) * 100

In [ ]:
qty = 200
long_open_price = 0.4941
long_open_fee = qty * long_open_price * long_open_fee_perc
short_open_price = 0.4903
short_open_fee_perc = 0.1 / 100 # 0.012114 usdt, limit order
short_open_fee = qty * short_open_price * short_open_fee_perc
open_diff = (short_open_price / long_open_price - 1) * 100

In [ ]:
long_open_fee, short_open_fee

In [ ]:
long_close_price = 0.4760
long_close_fee_perc = 0.02 / 100
long_close_fee = qty * long_close_price * long_close_fee_perc
short_close_price = 0.4752
short_close_fee_perc = 0.036 / 100 # market order
short_close_fee = qty * short_close_price * short_close_fee_perc
close_diff = (long_close_price / short_close_price - 1) * 100

In [ ]:
close_diff

In [ ]:
long_close_fee, short_close_fee

In [ ]:
long_profit = qty * (long_close_price - long_open_price) - long_open_fee - long_close_fee
short_profit = qty * (short_open_price - short_close_price) - short_open_fee - short_close_fee
long_profit, short_profit

In [ ]:
long_close_fee * long_close_price, short_close_price * short_close_fee

In [ ]:
long_fund_perc = -1.246 / 100
long_funding = -qty * long_fund_perc * long_open_price

short_fund_perc = -0.202 / 100
short_funding = qty * short_fund_perc * short_open_price
funding_profit = long_funding + short_funding

In [ ]:
long_funding, short_funding

In [ ]:
print(f'Доход по лонг-рынку: {long_profit:.3f} {long_funding:.3f} (фандинг)')
print(f'Доход по шорт-рынку: {short_profit:.3f} {short_funding:.3f} (фандинг)')
print(f'Доход только по фандингу: {funding_profit:.3f}')
print(f'Итого: {long_profit + short_profit + funding_profit:.3f}')

#### Spot-futures arbitrage

In [ ]:
from jaref_bot.data.http_api import ExchangeManager, BybitRestAPI, GateIORestAPI

import matplotlib.pyplot as plt

import pandas as pd
import polars as pl
import numpy as np
from datetime import datetime

exc_manager = ExchangeManager()
exc_manager.add_market("bybit_linear", BybitRestAPI('linear'))
exc_manager.add_market("bybit_spot", BybitRestAPI('spot'))

In [ ]:
interval = '1m'
n_iters = 1
sym = 'OM_USDT'

bb_lin, bb_spot = await exc_manager.get_candles(symbol=sym, interval=interval, n_iters=n_iters)

In [ ]:
cols = ['High', 'Low', 'Close']
df = bb_spot[cols].merge(bb_lin[cols], on='Date', suffixes=('_spot', '_fut'))
df['close_diff'] = (df['Close_spot'] / df['Close_fut'] - 1) * 100
df['max_diff'] = (df['High_spot'] / df['Low_fut'] - 1) * 100
df['min_diff'] = (df['Low_spot'] / df['High_fut'] - 1) * 100

In [ ]:
df[['max_diff', 'min_diff', 'close_diff']].plot(figsize=(14, 4));
plt.axhline(y=df['close_diff'].median(), color='black', linestyle='-') # mean
plt.axhline(y=0, color='red', linestyle='-'); # mean